import type { Raw } from './content';

/**
 * Every sentence that can fly, with who it's said to (see the content library).
 * Notation (see parse()): tokens split by " | "; "!toxic→honest version";
 * "~sweet with a sting→honest version" (looks friendly, still hurts);
 * "+feeling"; anything else neutral. Hebrew writes the speaker's gender as
 * {m|f}; the listener's is fixed by the face.
 */
export const RAW: Raw[] = [
  {
    id: 'room-never', with: ['teen'], face: 'teen', topics: ['chores', 'mess'], setting: 'home', diff: 1,
    en: '!You never clean→I’d be glad if you cleaned | your room | !— not once!→— this week.',
    he: '!אתה אף פעם לא מסדר→הייתי {שמח|שמחה} אם תסדר | את החדר שלך | !— אף פעם!→— השבוע.',
    ar: '!أنت لا ترتب أبدًا→أتمنى أن ترتب | غرفتك | !— ولا مرة!→— هذا الأسبوع.',
  },
  {
    id: 'shoes-always', with: ['child'], face: 'child', topics: ['mess'], setting: 'home', diff: 1,
    en: '!You ALWAYS leave→I keep tripping over | your shoes | in the hallway | +— please put them away.',
    he: '!אתה תמיד משאיר את הנעליים→אני כל הזמן {נתקל|נתקלת} בנעליים | במסדרון | +— בבקשה תשים אותן בארון.',
    ar: '!أنت دائمًا تترك حذاءك→أتعثّر دائمًا بحذائك | في الممر | +— أرجوك ضعه في مكانه.',
  },
  {
    id: 'listen-never', with: ['teen'], face: 'teen', topics: ['respect'], setting: 'home', diff: 1,
    en: '!You NEVER listen→I don’t feel heard | when I ask | for help | +— it matters to me.',
    he: '!אתה אף פעם לא מקשיב→אני לא {מרגיש|מרגישה} שמקשיבים לי | כשאני {מבקש|מבקשת} | עזרה | +— זה חשוב לי.',
    ar: '!أنت لا تسمعني أبدًا→لا أشعر أنك تسمعني | عندما أطلب | المساعدة | +— هذا مهم لي.',
  },
  {
    id: 'phone-always', with: ['partner'], face: 'partner', topics: ['screens', 'connection'], setting: 'home', diff: 1,
    en: '!You’re ALWAYS on your phone→Lately there’s a lot of phone between us | !— always!→— and I miss you.',
    he: '!תמיד את/ה בטלפון→לאחרונה יש הרבה טלפון בינינו | !— כל הזמן!→— ואני {מתגעגע|מתגעגעת}.',
    ar: '!أنت دائمًا على الهاتف→مؤخرًا الهاتف بيننا كثيرًا | !— دائمًا!→— وأشتاق إليك.',
  },
  {
    id: 'dishes-never', with: ['child'], face: 'child', topics: ['chores'], setting: 'home', diff: 1,
    en: '!You never clear→It would help me if you cleared | the dishes | !— ever!→— tonight.',
    he: '!אתה אף פעם לא מפנה→יעזור לי אם תפנה | את הכלים | !— אף פעם!→— הערב.',
    ar: '!أنت لا ترفع أبدًا→سيساعدني أن ترفع | الصحون | !— أبدًا!→— الليلة.',
  },
  {
    id: 'tired-help', with: ['partner'], face: 'partner', topics: ['chores', 'mealtime'], setting: 'home', diff: 2,
    en: '+I’m tired | and | !you NEVER help→I could really use help | with dinner.',
    he: '+אני {עייף|עייפה} | ו | !את/ה אף פעם לא עוזר/ת→ממש {אשמח|אשמח} לעזרה | עם ארוחת הערב.',
    ar: '+أنا متعب | و | !أنت لا تساعد أبدًا→أحتاج حقًا إلى مساعدة | في العشاء.',
  },
  {
    id: 'worried-late', with: ['teen'], face: 'teen', topics: ['independence'], setting: 'home', diff: 2,
    en: '+I feel worried | when | !you’re ALWAYS out late→you come home late | and don’t call.',
    he: '+אני {דואג|דואגת} | כש | !אתה תמיד חוזר מאוחר→אתה חוזר מאוחר | ולא מתקשר.',
    ar: '+أنا قلق | عندما | !تتأخر دائمًا→تعود متأخرًا | ولا تتصل.',
  },
  {
    id: 'five-minutes', with: ['child'], face: 'child', topics: ['noise'], setting: 'home', diff: 2,
    en: '+Please | !stop being so annoying→give me five quiet minutes | +— I need it.',
    he: '+בבקשה | !תפסיק להיות כזה מעצבן→תן לי חמש דקות שקט | +— אני {צריך|צריכה} את זה.',
    ar: '+من فضلك | !كفّ عن إزعاجي→أعطني خمس دقائق هدوء | +— أحتاج ذلك.',
  },
  {
    id: 'lazy-toys', with: ['young-child'], face: 'child', topics: ['mess'], setting: 'home', diff: 3,
    en: '!You’re so lazy!→I’m exhausted | — the toys | are still | on the floor.',
    he: '!אתה כזה עצלן!→אני {גמור|גמורה} מעייפות | — הצעצועים | עדיין | על הרצפה.',
    ar: '!أنت كسول جدًا!→أنا منهك | — الألعاب | ما زالت | على الأرض.',
  },
  {
    id: 'baby', with: ['child'], face: 'child', topics: ['homework'], setting: 'home', diff: 3,
    en: '!What are you, a baby?→I can see it’s hard. | Let’s | try again | +together.',
    he: '!מה אתה, תינוק?→אני {רואה|רואה} שזה קשה. | בוא | ננסה שוב | +ביחד.',
    ar: '!ماذا، هل أنت طفل؟→أرى أن الأمر صعب. | هيا | نحاول مجددًا | +معًا.',
  },
  {
    id: 'ridiculous', with: ['partner'], face: 'partner', topics: ['respect'], setting: 'home', diff: 3,
    en: '!That’s ridiculous!→I see it differently. | +I feel hurt | when | !you mock me→my ideas get laughed at.',
    he: '!זה מגוחך!→אני {רואה|רואה} את זה אחרת. | +אני {מרגיש|מרגישה} {פגוע|פגועה} | כש | !את/ה לועג/ת לי→צוחקים על הרעיונות שלי.',
    ar: '!هذا سخيف!→أرى الأمر بشكل مختلف. | +أشعر بالأذى | عندما | !تسخر مني→يُضحك على أفكاري.',
  },
  {
    id: 'impossible-screens', with: ['child'], face: 'child', topics: ['screens'], setting: 'home', diff: 3,
    en: '!You’re impossible!→I’m at the end of my rope. | Screens | off | +— please.',
    he: '!אתה בלתי אפשרי!→נגמר לי הכוח. | מסכים | כבים | +— בבקשה.',
    ar: '!أنت مستحيل!→نفد صبري. | الشاشات | تُطفأ | +— من فضلك.',
  },
  {
    id: 'selfish-groceries', with: ['teen'], face: 'teen', topics: ['chores'], setting: 'home', diff: 3,
    en: '!Stop being so selfish→I need a hand | with the groceries | +— thank you!',
    he: '!תפסיק להיות כזה אנוכי→אני {צריך|צריכה} עזרה | עם הקניות | +— תודה!',
    ar: '!كفّ عن الأنانية→أحتاج مساعدة | في المشتريات | +— شكرًا!',
  },
  {
    id: 'spill-thanks', with: ['young-child'], face: 'child', topics: ['mealtime'], setting: 'home', diff: 4,
    en: '+Thank you | for trying, | !but you ALWAYS spill→and next time let’s use | the small cup.',
    he: '+תודה | שניסית, | !אבל אתה תמיד שופך→ובפעם הבאה ניקח | את הכוס הקטנה.',
    ar: '+شكرًا لك | لأنك حاولت، | !لكنك دائمًا تسكب→والمرة القادمة لنأخذ | الكوب الصغير.',
  },
  {
    id: 'notice', with: ['partner'], face: 'partner', topics: ['mental-load', 'connection'], setting: 'home', diff: 4,
    en: '+You matter to me, | !and you NEVER notice→and I need you to notice | when I’m | overwhelmed.',
    he: '+אכפת לי ממך, | !ואת/ה אף פעם לא שם/ה לב→ואני {צריך|צריכה} שתשים/י לב | כשאני | {מוצף|מוצפת}.',
    ar: '+أنت تهمّني، | !وأنت لا تلاحظ أبدًا→وأحتاج أن تلاحظ | عندما أكون | مرهقًا.',
  },
  {
    id: 'hide-things', with: ['teen-girl'], face: 'teenGirl', topics: ['honesty'], setting: 'home', diff: 4,
    en: '+Thank you for telling me. | !You ALWAYS hide things→I’d rather hear things | from you | +first.',
    he: '+תודה שסיפרת לי. | !את תמיד מסתירה ממני→הייתי {מעדיף|מעדיפה} לשמוע | ממך | +קודם.',
    ar: '+شكرًا لأنك أخبرتني. | !أنتِ دائمًا تخفين الأشياء→أفضّل أن أسمع | منكِ | +أولًا.',
  },
  {
    id: 'ungrateful', with: ['teen'], face: 'teen', topics: ['respect'], setting: 'home', diff: 4,
    en: '!You never→It’s rare that you | say | +thank you, | !you ungrateful kid→and I’d love to hear it.',
    he: '!אף פעם אתה לא→רק לעתים רחוקות אתה | אומר | +תודה, | !ילד כפוי טובה→והייתי {שמח|שמחה} לשמוע.',
    ar: '!أنت لا تقول أبدًا→نادرًا ما تقول | +شكرًا، | !يا ناكر الجميل→وأحب أن أسمعها.',
  },
  {
    id: 'bills', with: ['partner'], face: 'partner', topics: ['money'], setting: 'home', diff: 5, heavy: true,
    en: '!You ALWAYS do this!→This keeps happening, | +and I feel alone | with the bills. | !You NEVER care→I need us to sit down | together | +— tonight?',
    he: '!את/ה תמיד עושה את זה!→זה קורה שוב ושוב, | +ואני {מרגיש|מרגישה} לבד | עם החשבונות. | !לא אכפת לך בכלל→אני {צריך|צריכה} שנשב | ביחד | +— הערב?',
    ar: '!أنت دائمًا تفعل هذا!→هذا يتكرر، | +وأشعر بالوحدة | مع الفواتير. | !أنت لا تهتم أبدًا→أحتاج أن نجلس | معًا | +— الليلة؟',
  },
  {
    id: 'grounded', with: ['teen'], face: 'teen', topics: ['independence'], setting: 'home', diff: 5,
    en: '!You’re grounded forever!→I get scared | when you | don’t answer | your phone. | !You NEVER think→Next time, | a text | +is enough.',
    he: '!אתה מרותק לנצח!→אני {נבהל|נבהלת} | כשאתה | לא עונה | לטלפון. | !אתה אף פעם לא חושב→בפעם הבאה, | הודעה | +מספיקה.',
    ar: '!أنت معاقب إلى الأبد!→أخاف | عندما | لا تردّ | على هاتفك. | !أنت لا تفكر أبدًا→في المرة القادمة، | رسالة | +تكفي.',
  },
  {
    id: 'criticize-cooking', with: ['ageing-parent'], face: 'grandma', topics: ['respect'], setting: 'home', diff: 5,
    en: '!You ALWAYS criticize me!→It stings | when | my cooking | gets comments. | +I love you | !but stop it→and I’d love a compliment | +sometimes.',
    he: '!את תמיד מבקרת אותי!→זה צורב | כש | על הבישול שלי | יש הערות. | +אני {אוהב|אוהבת} אותך | !אבל די כבר→והייתי {שמח|שמחה} למחמאה | +לפעמים.',
    ar: '!أنتِ دائمًا تنتقدينني!→يؤلمني | عندما | طبخي | يُنتقد. | +أحبك | !لكن كفى→وأحب مديحًا | +أحيانًا.',
  },
  {
    id: 'yc-shoes-on', with: ['young-child'], face: 'child', topics: ['morning-rush'], setting: 'home', diff: 1,
    en: '!You NEVER put your shoes on→Shoes on | now, | sweetie | +— we’re leaving.',
    he: '!אתה אף פעם לא נועל נעליים→נועלים נעליים | עכשיו, | מתוק | +— אנחנו יוצאים.',
    ar: '!أنت لا تلبس حذاءك أبدًا→نلبس الحذاء | الآن، | يا حبيبي | +— سنخرج.',
  },
  {
    id: 'yc-bedtime', with: ['young-child'], face: 'child', topics: ['bedtime'], setting: 'home', diff: 2,
    en: '+I love you | and | !you’re driving me crazy→it’s time | to sleep | now.',
    he: '+אני {אוהב|אוהבת} אותך | ו | !אתה משגע אותי→זה זמן | לישון | עכשיו.',
    ar: '+أحبك | و | !أنت تجنّنني→حان وقت | النوم | الآن.',
  },
  {
    id: 'yc-crybaby', with: ['young-child'], face: 'child', topics: ['public'], setting: 'public', diff: 3,
    en: '!Stop being a crybaby!→I see you’re upset. | We’re not buying | candy | +— I’m here with you.',
    he: '!תפסיק להיות בכיין!→אני {רואה|רואה} שאתה כועס. | לא קונים | ממתק | +— אני פה איתך.',
    ar: '!كفّ عن البكاء كالرضّع!→أرى أنك منزعج. | لن نشتري | الحلوى | +— أنا هنا معك.',
  },
  {
    id: 'yc-bad-boy', with: ['young-child'], face: 'child', topics: ['siblings'], setting: 'home', diff: 3, heavy: true,
    en: '!You’re a bad boy!→Hitting | hurts. | +I won’t let you | hit your sister.',
    he: '!אתה ילד רע!→מכות | כואבות. | +אני לא {אתן|אתן} לך | להרביץ לאחות שלך.',
    ar: '!أنت ولد سيئ!→الضرب | يؤلم. | +لن أسمح لك | بضرب أختك.',
  },
  {
    id: 'yc-sting-great', with: ['young-child'], face: 'child', topics: ['mess'], setting: 'home', diff: 5,
    en: '~Oh great, another mess, wonderful→The paint | is on the wall. | +I’m frustrated. | Let’s get | a cloth | +together.',
    he: '~יופי, עוד בלגן, נפלא→הצבע | על הקיר. | +אני {מתוסכל|מתוסכלת}. | בוא נביא | סמרטוט | +ביחד.',
    ar: '~رائع، فوضى أخرى، ممتاز→الألوان | على الحائط. | +أنا محبط. | تعال نحضر | قطعة قماش | +معًا.',
  },
  {
    id: 'yc-double', with: ['young-child'], face: 'child', topics: ['bedtime'], setting: 'home', diff: 4,
    en: '+I know you’re thirsty, | !but this is the TENTH time→and this is the last drink. | !You NEVER sleep→Now we sleep.',
    he: '+אני {יודע|יודעת} שאתה צמא, | !אבל זו הפעם העשירית→וזו השתייה האחרונה. | !אתה אף פעם לא ישן→עכשיו ישנים.',
    ar: '+أعرف أنك عطشان، | !لكنها المرة العاشرة→وهذا آخر شراب. | !أنت لا تنام أبدًا→الآن ننام.',
  },
  {
    id: 'ch-homework', with: ['child'], face: 'child', topics: ['homework'], setting: 'home', diff: 2,
    en: '+I’m frustrated | and | !you’re not even trying→this page | is taking long. | Let’s take | a break.',
    he: '+אני {מתוסכל|מתוסכלת} | ו | !אתה אפילו לא מנסה→הדף הזה | לוקח הרבה זמן. | בוא ניקח | הפסקה.',
    ar: '+أنا محبط | و | !أنت لا تحاول حتى→هذه الصفحة | تأخذ وقتًا طويلًا. | لنأخذ | استراحة.',
  },
  {
    id: 'ch-liar', with: ['child'], face: 'child', topics: ['honesty', 'bedtime'], setting: 'home', diff: 3,
    en: '!You little liar!→The toothbrush | is dry. | Let’s brush | +together | now.',
    he: '!שקרן קטן!→המברשת | יבשה. | בוא נצחצח | +ביחד | עכשיו.',
    ar: '!يا كذّاب صغير!→فرشاة الأسنان | جافة. | تعال نفرّش | +معًا | الآن.',
  },
  {
    id: 'ch-gym', with: ['child'], face: 'child', topics: ['morning-rush'], setting: 'home', diff: 4,
    en: '+I get it, mornings are hard, | !but you ALWAYS forget→and tomorrow | let’s pack | the gym bag | +at night.',
    he: '+אני {מבין|מבינה}, בקרים קשים, | !אבל אתה תמיד שוכח→ומחר | נארוז | את תיק הספורט | +בערב.',
    ar: '+أفهم، الصباحات صعبة، | !لكنك دائمًا تنسى→وغدًا | نحضّر | حقيبة الرياضة | +مساءً.',
  },
  {
    id: 'ch-sting-room', with: ['child'], face: 'child', topics: ['chores', 'mess'], setting: 'home', diff: 5,
    en: '~Wow, what a SPOTLESS room→The room | still needs | five minutes. | +I’ll help you | start. | !You NEVER finish→Then we play.',
    he: '~וואו, איזה חדר נקי לגמרי→החדר | עוד צריך | חמש דקות. | +אני {אעזור|אעזור} לך | להתחיל. | !אתה אף פעם לא מסיים→ואז משחקים.',
    ar: '~واو، يا لها من غرفة نظيفة تمامًا→الغرفة | ما زالت تحتاج | خمس دقائق. | +سأساعدك | لتبدأ. | !أنت لا تنهي أبدًا→ثم نلعب.',
  },
  {
    id: 'kids-fight', with: ['kids'], face: 'child', topics: ['siblings', 'noise'], setting: 'home', diff: 2,
    en: '+I’m on a call | and | !you two are monsters→it’s loud. | Five minutes | +of quiet, please.',
    he: '+אני בשיחה | ו | !שניכם מפלצות→רועש פה. | חמש דקות | +שקט, בבקשה.',
    ar: '+أنا في مكالمة | و | !أنتما وحشان→الصوت عالٍ. | خمس دقائق | +هدوء، من فضلكما.',
  },
  {
    id: 'tn-phone-night', with: ['teen'], face: 'teen', topics: ['screens', 'bedtime'], setting: 'home', diff: 2,
    en: '+I’m worried | about your sleep | and | !you’re addicted→the phone | stays in the kitchen | at night.',
    he: '+אני {דואג|דואגת} | לשינה שלך | ו | !אתה מכור→הטלפון | נשאר במטבח | בלילה.',
    ar: '+أنا قلق | على نومك | و | !أنت مدمن→الهاتف | يبقى في المطبخ | ليلًا.',
  },
  {
    id: 'tn-eyeroll', with: ['teen-girl'], face: 'teenGirl', topics: ['respect', 'chores'], setting: 'home', diff: 3,
    en: '!Don’t you roll your eyes at me!→I see you’re annoyed. | The dishwasher | still | +needs a hand.',
    he: '!אל תגלגלי עליי עיניים!→אני {רואה|רואה} שאת מתעצבנת. | המדיח | עדיין | +צריך עזרה.',
    ar: '!لا تدحرجي عينيكِ في وجهي!→أرى أنكِ منزعجة. | غسالة الصحون | ما زالت | +تحتاج مساعدة.',
  },
  {
    id: 'tn-sting-ride', with: ['teen'], face: 'teen', topics: ['independence', 'work-life'], setting: 'home', diff: 5,
    en: '~Sure, I’m your personal taxi→I have a meeting | in ten minutes. | +I want to help, | so | next time | ask | +earlier.',
    he: '~בטח, אני נהג המונית הפרטי שלך→יש לי פגישה | בעוד עשר דקות. | +אני {רוצה|רוצה} לעזור, | אז | בפעם הבאה | תבקש | +מוקדם יותר.',
    ar: '~طبعًا، أنا سائق الأجرة الخاص بك→عندي اجتماع | بعد عشر دقائق. | +أريد أن أساعد، | لذا | في المرة القادمة | اطلب | +مبكرًا.',
  },
  {
    id: 'tn-test', with: ['teen'], face: 'teen', topics: ['honesty', 'homework'], setting: 'home', diff: 4, heavy: true,
    en: '+I’m not angry about the grade, | !but you’re a sneaky liar→I was hurt | that you hid it. | +Let’s look at it | together.',
    he: '+אני לא {כועס|כועסת} על הציון, | !אבל אתה שקרן ערמומי→{נפגעתי|נפגעתי} | שהסתרת. | +בוא נסתכל על זה | ביחד.',
    ar: '+لست غاضبًا من العلامة، | !لكنك كاذب ماكر→تأذّيت | لأنك أخفيتها. | +لننظر إليها | معًا.',
  },
  {
    id: 'pt-dishes', with: ['partner'], face: 'partner', topics: ['chores'], setting: 'home', diff: 1,
    en: '!You NEVER do the dishes→The sink | is full | since this morning | +— could you take it?',
    he: '!את/ה אף פעם לא שוטף/ת כלים→הכיור | מלא | מהבוקר | +— תוכל/י לקחת את זה?',
    ar: '!أنت لا تغسل الصحون أبدًا→المغسلة | ممتلئة | منذ الصباح | +— هل تتولّاها؟',
  },
  {
    id: 'pt-late', with: ['partner'], face: 'partner', topics: ['mealtime', 'work-life'], setting: 'home', diff: 2,
    en: '+I was worried | and | !you’re so inconsiderate→dinner waited | an hour | with no message.',
    he: '+{דאגתי|דאגתי} | ו | !את/ה כל כך לא מתחשב/ת→הארוחה חיכתה | שעה | בלי הודעה.',
    ar: '+كنت قلقًا | و | !أنت لا تراعي أحدًا→انتظر العشاء | ساعة | بلا رسالة.',
  },
  {
    id: 'pt-scrolling', with: ['partner'], face: 'partner', topics: ['screens', 'connection'], setting: 'home', diff: 3,
    en: '!You’re a zombie with that phone!→I’m telling you | about my day | +and I need | your eyes | for a minute.',
    he: '!את/ה זומבי עם הטלפון הזה!→אני {מספר|מספרת} לך | על היום שלי | +ואני {צריך|צריכה} | את העיניים שלך | לדקה.',
    ar: '!أنت كالزومبي مع هذا الهاتف!→أحكي لك | عن يومي | +وأحتاج | عينيك | لدقيقة.',
  },
  {
    id: 'pt-plans', with: ['partner'], face: 'partner', topics: ['connection'], setting: 'home', diff: 4,
    en: '+I’m glad you have friends, | !but you ALWAYS choose them→and I hoped | for a day | +just for us.',
    he: '+אני {שמח|שמחה} שיש לך חברים, | !אבל את/ה תמיד בוחר/ת בהם→ו{קיוויתי|קיוויתי} | ליום | +רק שלנו.',
    ar: '+يسعدني أن لديك أصدقاء، | !لكنك دائمًا تختارهم→وكنت آمل | بيوم | +لنا فقط.',
  },
  {
    id: 'pt-sting-purchase', with: ['partner'], face: 'partner', topics: ['money'], setting: 'home', diff: 5, heavy: true,
    en: '~Nice new toy, I’m SO happy for you→I saw the charge | on the card. | +I got stressed. | !You NEVER ask me→Big purchases | we decide | +together.',
    he: '~צעצוע חדש ויפה, אני כל כך {שמח|שמחה} בשבילך→{ראיתי|ראיתי} את החיוב | בכרטיס. | +{נלחצתי|נלחצתי}. | !את/ה אף פעם לא שואל/ת אותי→קניות גדולות | מחליטים | +ביחד.',
    ar: '~لعبة جديدة جميلة، أنا سعيد جدًا لأجلك→رأيت المبلغ | على البطاقة. | +توتّرت. | !أنت لا تسألني أبدًا→المشتريات الكبيرة | نقرّرها | +معًا.',
  },
  {
    id: 'pt-towel', with: ['partner'], face: 'partner', topics: ['mess', 'household'], setting: 'home', diff: 3,
    en: '!You’re such a slob!→The wet towel | on the bed | makes my side | wet. | +Could you hang it?',
    he: '!את/ה כזה/כזאת מרושל/ת!→המגבת הרטובה | על המיטה | מרטיבה | את הצד שלי. | +תוכל/י לתלות אותה?',
    ar: '!أنت فوضوي جدًا!→المنشفة المبللة | على السرير | تبلّل | جهتي. | +هل تعلّقها؟',
  },
  {
    id: 'pt-anniversary', with: ['partner'], face: 'partner', topics: ['connection'], setting: 'public', diff: 5,
    en: '!You ALWAYS forget what matters to me!→No table tonight. | +I’m disappointed. | !You’re hopeless→Let’s find | another place | +— the evening | is ours.',
    he: '!את/ה תמיד שוכח/ת מה חשוב לי!→אין שולחן הערב. | +אני {מאוכזב|מאוכזבת}. | !את/ה חסר/ת תקנה→בוא/י נמצא | מקום אחר | +— הערב | שלנו.',
    ar: '!أنت دائمًا تنسى ما يهمّني!→لا طاولة الليلة. | +أنا خائب الأمل. | !أنت ميؤوس منك→لنجد | مكانًا آخر | +— الأمسية | لنا.',
  },
  {
    id: 'pt-overrule', with: ['partner'], requires: ['parent-young-child', 'parent-school-age', 'parent-teen', 'single-parent'], face: 'partner', topics: ['respect'], setting: 'home', diff: 4,
    en: '+I know you meant well, | !but you ALWAYS undermine me→and I need us | to agree | in front of the kids.',
    he: '+אני {יודע|יודעת} שהתכוונת לטובה, | !אבל את/ה תמיד מבטל/ת אותי→ואני {צריך|צריכה} שנסכים | מול הילדים.',
    ar: '+أعرف أن نيّتك حسنة، | !لكنك دائمًا تُضعف كلامي→وأحتاج أن نتّفق | أمام الأولاد.',
  },
  {
    id: 'ap-same-question', with: ['ageing-parent'], face: 'grandma', topics: ['caregiving', 'health'], setting: 'home', diff: 2, heavy: true,
    en: '+I’m tired, Mom, | and | !you NEVER remember→today is Tuesday. | +I’m here.',
    he: '+אני {עייף|עייפה}, אמא, | ו | !את אף פעם לא זוכרת→היום יום שלישי. | +אני פה.',
    ar: '+أنا متعب يا أمي، | و | !أنتِ لا تتذكّرين أبدًا→اليوم الثلاثاء. | +أنا هنا.',
  },
  {
    id: 'ap-calls', with: ['ageing-parent'], face: 'grandpa', topics: ['caregiving', 'work-life'], setting: 'work', diff: 1,
    en: '!You ALWAYS call at work!→I’m in the middle | of a meeting, Dad. | I’ll call back | +at six.',
    he: '!אתה תמיד מתקשר בעבודה!→אני באמצע | ישיבה, אבא. | {אחזור|אחזור} אליך | +בשש.',
    ar: '!أنت دائمًا تتصل وأنا في العمل!→أنا في منتصف | اجتماع يا أبي. | سأعاود الاتصال | +في السادسة.',
  },
  {
    id: 'ap-stubborn', with: ['ageing-parent'], face: 'grandpa', topics: ['caregiving', 'health', 'independence'], setting: 'home', diff: 3, heavy: true,
    en: '!You’re a stubborn old man!→I’m worried | about the driving. | +I love you | and | I want you | safe.',
    he: '!אתה זקן עקשן!→אני {דואג|דואגת} | בגלל הנהיגה. | +אני {אוהב|אוהבת} אותך | ו | אני {רוצה|רוצה} | שתהיה בטוח.',
    ar: '!أنت عجوز عنيد!→أنا قلق | بشأن القيادة. | +أحبك | و | أريدك | بأمان.',
  },
  {
    id: 'ap-doctor', with: ['ageing-parent'], face: 'grandma', topics: ['caregiving', 'health'], setting: 'home', diff: 4, heavy: true,
    en: '+I respect your choices, | !but you’re being impossible→and I’m scared. | +I’ll come | with you | to the doctor.',
    he: '+אני {מכבד|מכבדת} את הבחירות שלך, | !אבל את בלתי אפשרית→ואני {מפחד|מפחדת}. | +{אבוא|אבוא} | איתך | לרופא.',
    ar: '+أحترم خياراتك، | !لكنكِ مستحيلة→وأنا خائف. | +سآتي | معكِ | إلى الطبيب.',
  },
  {
    id: 'ap-sting-visit', with: ['ageing-parent'], face: 'grandpa', topics: ['caregiving', 'connection'], setting: 'public', diff: 5, heavy: true,
    en: '~Sure, Dad, I NEVER visit, you’re right→I was here | yesterday | and the day before. | +When you say that | it hurts. | Do you need | +more of me?',
    he: '~בטח, אבא, אני אף פעם לא {מבקר|מבקרת}, צודק→{הייתי|הייתי} פה | אתמול | ושלשום. | +כשאתה אומר את זה | זה כואב. | אתה צריך | +אותי יותר?',
    ar: '~طبعًا يا أبي، أنا لا أزورك أبدًا، معك حق→كنت هنا | أمس | وأول أمس. | +حين تقول ذلك | يؤلمني. | هل تحتاجني | +أكثر؟',
  },
  {
    id: 'gc-screens', with: ['grandchild'], face: 'child', topics: ['screens', 'connection'], setting: 'home', diff: 1,
    en: '!You’re ALWAYS on that phone→I missed you! | Phones | in the basket | +— I have a game.',
    he: '!אתה תמיד בטלפון הזה→{התגעגעתי|התגעגעתי}! | טלפונים | לסלסלה | +— יש לי משחק.',
    ar: '!أنت دائمًا على هذا الهاتف→اشتقت إليك! | الهواتف | في السلة | +— عندي لعبة.',
  },
  {
    id: 'gc-bedtime', with: ['grandchild'], face: 'child', topics: ['bedtime'], setting: 'home', diff: 2,
    en: '+I love having you here | and | !you’re a little monster→at my place | we sleep | at nine.',
    he: '+כיף לי שאתה פה | ו | !אתה מפלצת קטנה→אצלי | ישנים | בתשע.',
    ar: '+أحبّ وجودك هنا | و | !أنت وحش صغير→عندي | ننام | في التاسعة.',
  },
  {
    id: 'gc-sting', with: ['grandchild'], face: 'child', topics: ['respect'], setting: 'home', diff: 4,
    en: '+Thank you for coming, | !you spoiled brat→and | in my house | we say | +please.',
    he: '+תודה שבאת, | !ילד מפונק→ו | בבית שלי | אומרים | +בבקשה.',
    ar: '+شكرًا لأنك أتيت، | !يا ولد مدلّل→و | في بيتي | نقول | +من فضلك.',
  },
  {
    id: 'rm-dishes', with: ['roommate'], face: 'man', topics: ['chores', 'mess'], setting: 'home', diff: 1,
    en: '!You NEVER wash your dishes→The sink | has been full | for four days | +— can we make a rule?',
    he: '!אתה אף פעם לא שוטף כלים→הכיור | מלא | כבר ארבעה ימים | +— נקבע כלל?',
    ar: '!أنت لا تغسل صحونك أبدًا→المغسلة | ممتلئة | منذ أربعة أيام | +— هل نضع قاعدة؟',
  },
  {
    id: 'rm-food', with: ['roommate'], face: 'woman', topics: ['household'], setting: 'home', diff: 2,
    en: '+I was annoyed | when | !you stole my food→my cheese was gone. | A shelf | +for each of us?',
    he: '+{התעצבנתי|התעצבנתי} | כש | !גנבת לי את האוכל→הגבינה שלי נגמרה. | מדף | +לכל אחת?',
    ar: '+انزعجت | عندما | !سرقتِ طعامي→نفدت جبنتي. | رفّ | +لكل واحدة؟',
  },
  {
    id: 'rm-rent', with: ['roommate'], face: 'man', topics: ['money'], setting: 'home', diff: 3, heavy: true,
    en: '!You’re a freeloader!→Rent is due tomorrow | and | +I can’t cover | your share | again.',
    he: '!אתה פרזיט!→השכירות מחר | ו | +אני לא {יכול|יכולה} לכסות | את החלק שלך | שוב.',
    ar: '!أنت طفيلي!→الإيجار غدًا | و | +لا أستطيع تغطية | حصتك | مرة أخرى.',
  },
  {
    id: 'rm-exam', with: ['roommate'], face: 'woman', topics: ['noise'], setting: 'home', diff: 4,
    en: '+I’m glad you have friends over, | !but you’re SO selfish→and I have an exam | tomorrow. | +Quieter after ten?',
    he: '+אני {שמח|שמחה} שיש לך חברים, | !אבל את כזאת אנוכית→ויש לי מבחן | מחר. | +יותר בשקט אחרי עשר?',
    ar: '+يسعدني أن عندك أصدقاء، | !لكنك أنانية جدًا→وعندي امتحان | غدًا. | +أهدأ بعد العاشرة؟',
  },
  {
    id: 'rm-sting-guest', with: ['roommate'], face: 'man', topics: ['household'], setting: 'home', diff: 5,
    en: '~Oh, does your girlfriend pay rent here too?→She’s here | every night | and | +I need to talk | about it. | !You NEVER ask→Can we sit | +tonight?',
    he: '~אה, החברה שלך משלמת פה שכירות גם?→היא פה | כל לילה | ו | +אני {צריך|צריכה} לדבר | על זה. | !אתה אף פעם לא שואל→נשב | +הערב?',
    ar: '~آه، هل صديقتك تدفع الإيجار هنا أيضًا؟→هي هنا | كل ليلة | و | +أحتاج أن نتحدث | عن ذلك. | !أنت لا تسأل أبدًا→هل نجلس | +الليلة؟',
  },
  {
    id: 'rm-mess', with: ['roommate'], face: 'woman', topics: ['mess'], setting: 'home', diff: 3,
    en: '!You’re a pig!→The living room | is full of | your stuff. | +Can we clear it | by tonight?',
    he: '!את חזירה!→הסלון | מלא | בדברים שלך. | +אפשר לפנות | עד הערב?',
    ar: '!أنتِ خنزيرة!→الصالة | مليئة | بأغراضك. | +هل نرتّبها | حتى المساء؟',
  },
  {
    id: 'boss-never-ask', with: ['boss'], face: 'man', topics: ['work'], setting: 'work', diff: 1,
    en: '!You NEVER ask me→I’d like to be asked | before | deadlines | are set.',
    he: '!אתה אף פעם לא שואל אותי→{אשמח|אשמח} שישאלו אותי | לפני | שקובעים | דדליין.',
    ar: '!أنت لا تسألني أبدًا→أودّ أن أُسأل | قبل | تحديد | المواعيد.',
  },
  {
    id: 'cowork-always-late', with: ['coworker'], face: 'woman', topics: ['work'], setting: 'work', diff: 1,
    en: '!You’re ALWAYS late→We started without you | to the meeting | !— every time!→— today.',
    he: '!את תמיד מאחרת→התחלנו בלעדייך | לישיבה | !— כל פעם!→— היום.',
    ar: '!أنتِ دائمًا متأخرة→بدأنا من دونك | الاجتماع | !— كل مرة!→— اليوم.',
  },
  {
    id: 'friend-never-call', with: ['friend'], face: 'man', topics: ['connection'], setting: 'online', diff: 1,
    en: '!You NEVER call me→I miss our talks | lately | !— never!→— let’s talk soon.',
    he: '!אתה אף פעם לא מתקשר→{מתגעגע|מתגעגעת} לשיחות שלנו | לאחרונה | !— אף פעם!→— בוא נדבר בקרוב.',
    ar: '!أنت لا تتصل أبدًا→اشتقت لأحاديثنا | مؤخرًا | !— أبدًا!→— لنتحدث قريبًا.',
  },
  {
    id: 'friend-always-cancel', with: ['friend'], face: 'woman', topics: ['connection'], setting: 'public', diff: 1,
    en: '!You ALWAYS cancel→It’s the third time | we planned | !and you bail→and I was looking forward to it.',
    he: '!את תמיד מבטלת→זו הפעם השלישית | שקבענו | !ואת מבריזה→ו{חיכיתי|חיכיתי} לזה.',
    ar: '!أنتِ دائمًا تلغين→إنها المرة الثالثة | التي نتفق فيها | !وتتهرّبين→وكنت أنتظر ذلك.',
  },
  {
    id: 'neighbor-always-noise', with: ['neighbor'], face: 'grandpa', topics: ['neighbors', 'noise'], setting: 'home', diff: 1,
    en: '!You ALWAYS make noise→The drilling | on Saturday | !— every week!→wakes me up early.',
    he: '!אתה תמיד עושה רעש→הקדיחה | בשבת | !— כל שבוע!→מעירה אותי מוקדם.',
    ar: '!أنت دائمًا تُحدث ضجيجًا→الحفر | يوم السبت | !— كل أسبوع!→يوقظني باكرًا.',
  },
  {
    id: 'neighbor-never-parking', with: ['neighbor'], face: 'man', topics: ['neighbors', 'road'], setting: 'home', diff: 1,
    en: '!You NEVER think of others→Your car | is blocking mine | !— again!→— could you move it?',
    he: '!אתה אף פעם לא חושב על אחרים→הרכב שלך | חוסם את שלי | !— שוב!→— תוכל להזיז?',
    ar: '!أنت لا تفكر بالآخرين أبدًا→سيارتك | تسدّ سيارتي | !— مرة أخرى!→— هل تحرّكها؟',
  },
  {
    id: 'family-always-advice', with: ['family'], face: 'grandma', topics: ['in-laws', 'respect'], setting: 'home', diff: 1,
    en: '!You ALWAYS tell me what to do→I’d like to decide | about my home | +myself.',
    he: '!את תמיד אומרת לי מה לעשות→{אשמח|אשמח} להחליט | על הבית שלי | +בעצמי.',
    ar: '!أنتِ دائمًا تقولين لي ماذا أفعل→أودّ أن أقرّر | بشأن بيتي | +بنفسي.',
  },
  {
    id: 'cowork-never-reply', with: ['coworker'], face: 'man', topics: ['work'], setting: 'online', diff: 1,
    en: '!You NEVER answer emails→I’m waiting on your answer | for the report | !— as usual!→— since Monday.',
    he: '!אתה אף פעם לא עונה למיילים→אני {מחכה|מחכה} לתשובה שלך | על הדוח | !— כרגיל!→— מיום שני.',
    ar: '!أنت لا تردّ على الرسائل أبدًا→أنتظر ردّك | بخصوص التقرير | !— كالعادة!→— منذ الاثنين.',
  },
  {
    id: 'family-never-visit', with: ['family'], face: 'man', topics: ['connection'], setting: 'home', diff: 1,
    en: '!You NEVER come over→It’s been months | since we sat | together | +— I miss you.',
    he: '!אתה אף פעם לא בא→עברו חודשים | מאז שישבנו | ביחד | +— אני {מתגעגע|מתגעגעת}.',
    ar: '!أنت لا تأتي أبدًا→مرّت أشهر | منذ جلسنا | معًا | +— اشتقت إليك.',
  },
  {
    id: 'friend-always-phone', with: ['friend'], face: 'woman', topics: ['connection', 'screens'], setting: 'public', diff: 1,
    en: '!You’re ALWAYS on your phone→I’d love your attention | while we’re | at dinner | +— I missed you.',
    he: '!את תמיד בטלפון→{אשמח|אשמח} לתשומת הלב שלך | כשאנחנו | בארוחה | +— התגעגעתי.',
    ar: '!أنتِ دائمًا على الهاتف→أودّ انتباهك | ونحن | على العشاء | +— اشتقت إليك.',
  },
  {
    id: 'boss-tired', with: ['boss'], face: 'woman', topics: ['work', 'work-life'], setting: 'work', diff: 2,
    en: '+I’m overloaded | and | !you just dump more on me→I need help choosing | what comes first.',
    he: '+אני {עמוס|עמוסה} | ו | !את רק זורקת עליי עוד→אני {צריך|צריכה} עזרה לבחור | מה קודם.',
    ar: '+أنا مثقل | و | !أنتِ ترمين عليّ المزيد→أحتاج مساعدة في الاختيار | ما الذي أولًا.',
  },
  {
    id: 'cowork-hurt-credit', with: ['coworker'], face: 'man', topics: ['work', 'respect'], setting: 'work', diff: 2,
    en: '+I felt hurt | when | !you stole my idea→my idea was presented | without my name.',
    he: '+{נפגעתי|נפגעתי} | כש | !גנבת לי את הרעיון→הרעיון שלי הוצג | בלי השם שלי.',
    ar: '+شعرت بالأذى | عندما | !سرقت فكرتي→عُرضت فكرتي | دون اسمي.',
  },
  {
    id: 'friend-worried', with: ['friend'], face: 'man', topics: ['connection'], setting: 'online', diff: 2,
    en: '+I was worried | when | !you just vanished→you didn’t answer | for three days.',
    he: '+{דאגתי|דאגתי} | כש | !פשוט נעלמת→לא ענית | שלושה ימים.',
    ar: '+كنت قلقًا | عندما | !اختفيت ببساطة→لم تردّ | ثلاثة أيام.',
  },
  {
    id: 'friend-lonely', with: ['friend'], face: 'woman', topics: ['connection'], setting: 'public', diff: 2,
    en: '+I felt alone | at the party | when | !you ignored me→you stayed with others | all night.',
    he: '+{הרגשתי|הרגשתי} לבד | במסיבה | כש | !התעלמת ממני→נשארת עם אחרים | כל הערב.',
    ar: '+شعرت بالوحدة | في الحفلة | عندما | !تجاهلتِني→بقيتِ مع الآخرين | طوال السهرة.',
  },
  {
    id: 'neighbor-tired', with: ['neighbor'], face: 'woman', topics: ['neighbors', 'noise'], setting: 'home', diff: 2,
    en: '+I’m exhausted | and | !your party was insane→the music went | until 2 a.m.',
    he: '+אני {גמור|גמורה} מעייפות | ו | !המסיבה שלך הייתה מטורפת→המוזיקה הייתה | עד שתיים בלילה.',
    ar: '+أنا منهك | و | !حفلتك كانت جنونية→الموسيقى استمرت | حتى الثانية ليلًا.',
  },
  {
    id: 'family-sad', with: ['family'], face: 'grandma', topics: ['respect'], setting: 'home', diff: 2,
    en: '+It makes me sad | when | !you compare me→I’m compared | to my brother.',
    he: '+עצוב לי | כש | !את משווה אותי→משווים אותי | לאח שלי.',
    ar: '+يحزنني | عندما | !تقارنينني→أُقارَن | بأخي.',
  },
  {
    id: 'stranger-scared', with: ['stranger'], face: 'man', topics: ['road'], setting: 'road', diff: 2,
    en: '+You scared me | — | !are you blind?!→you cut in | right in front of me.',
    he: '+הבהלת אותי | — | !אתה עיוור?!→נכנסת לי | ממש מקדימה.',
    ar: '+أخفتني | — | !هل أنت أعمى؟!→دخلت | أمامي مباشرة.',
  },
  {
    id: 'cowork-need-quiet', with: ['coworker'], face: 'woman', topics: ['work', 'noise'], setting: 'work', diff: 2,
    en: '+I need quiet | to focus | and | !you never shut up→the calls | on speaker | are hard for me.',
    he: '+אני {צריך|צריכה} שקט | כדי להתרכז | ו | !את לא סותמת לרגע→השיחות | על רמקול | קשות לי.',
    ar: '+أحتاج هدوءًا | كي أركّز | و | !لا تسكتين أبدًا→المكالمات | على مكبّر الصوت | صعبة عليّ.',
  },
  {
    id: 'friend-embarrassed', with: ['friend'], face: 'man', topics: ['respect'], setting: 'public', diff: 2,
    en: '+I was embarrassed | when | !you made fun of me→you told that story | in front of everyone.',
    he: '+הייתי {נבוך|נבוכה} | כש | !צחקת עליי→סיפרת את הסיפור הזה | מול כולם.',
    ar: '+شعرت بالإحراج | عندما | !سخرت مني→رويت تلك القصة | أمام الجميع.',
  },
  {
    id: 'boss-scared', with: ['boss'], face: 'man', topics: ['work'], setting: 'work', diff: 2,
    en: '+I get anxious | when | !you threaten me→I hear “we need to talk” | with no details.',
    he: '+אני {נלחץ|נלחצת} | כש | !אתה מאיים עליי→אני {שומע|שומעת} "צריך לדבר" | בלי פרטים.',
    ar: '+أتوتّر | عندما | !تهدّدني→أسمع «علينا أن نتكلم» | دون تفاصيل.',
  },
  {
    id: 'cowork-useless', with: ['coworker'], face: 'man', topics: ['work', 'respect'], setting: 'work', diff: 3,
    en: '!You’re useless!→The report is missing two parts | and | +I need it | by noon.',
    he: '!אתה חסר תועלת!→בדוח חסרים שני חלקים | ו | +אני {צריך|צריכה} אותו | עד הצהריים.',
    ar: '!أنت عديم الفائدة!→ينقص التقرير جزءان | و | +أحتاجه | حتى الظهر.',
  },
  {
    id: 'friend-selfish', with: ['friend'], face: 'woman', topics: ['connection'], setting: 'public', diff: 3,
    en: '!You’re so selfish!→It felt like | only your plans | counted | +— mine matter too.',
    he: '!את כזאת אנוכית!→{הרגשתי|הרגשתי} ש | רק התוכניות שלך | נחשבו | +— גם שלי חשובות.',
    ar: '!أنتِ أنانية جدًا!→شعرت أن | خططك فقط | كانت مهمة | +— خططي مهمة أيضًا.',
  },
  {
    id: 'neighbor-animal', with: ['neighbor'], face: 'man', topics: ['neighbors', 'mess'], setting: 'home', diff: 3,
    en: '!You live like an animal!→Your trash bag | has been in the stairwell | for three days.',
    he: '!אתה חי כמו חיה!→שקית הזבל שלך | בחדר המדרגות | כבר שלושה ימים.',
    ar: '!تعيش كالحيوانات!→كيس قمامتك | على الدرج | منذ ثلاثة أيام.',
  },
  {
    id: 'boss-clueless', with: ['boss'], face: 'woman', topics: ['work', 'respect'], setting: 'work', diff: 3,
    en: '!You have no clue!→I see it differently. | Can I show you | the numbers | +first?',
    he: '!אין לך מושג!→אני {רואה|רואה} את זה אחרת. | אפשר להראות לך | את המספרים | +קודם?',
    ar: '!ليس لديك أي فكرة!→أرى الأمر بشكل مختلف. | هل أريك | الأرقام | +أولًا؟',
  },
  {
    id: 'stranger-idiot', with: ['stranger'], face: 'man', topics: ['public'], setting: 'public', diff: 3,
    en: '!Are you an idiot?→Excuse me, | the line | starts | back there.',
    he: '!אתה אידיוט?→סליחה, | התור | מתחיל | שם מאחור.',
    ar: '!هل أنت غبي؟→عفوًا، | الطابور | يبدأ | من هناك.',
  },
  {
    id: 'family-nosy', with: ['family'], face: 'woman', topics: ['in-laws', 'respect'], setting: 'home', diff: 3,
    en: '!You’re so nosy!→That’s private for me, | and | +I’d rather | not talk about it.',
    he: '!את כזאת חטטנית!→זה פרטי בשבילי, | ו | +אני {מעדיף|מעדיפה} | לא לדבר על זה.',
    ar: '!أنتِ فضولية جدًا!→هذا أمر خاص بي، | و | +أفضّل | ألّا أتحدث عنه.',
  },
  {
    id: 'friend-liar', with: ['friend'], face: 'man', topics: ['honesty'], setting: 'public', diff: 3, heavy: true,
    en: '!You’re a liar!→I heard something different | from others | +and it confused me.',
    he: '!אתה שקרן!→{שמעתי|שמעתי} משהו אחר | מאחרים | +וזה בלבל אותי.',
    ar: '!أنت كاذب!→سمعت شيئًا مختلفًا | من الآخرين | +وهذا أربكني.',
  },
  {
    id: 'cowork-lazy', with: ['coworker'], face: 'woman', topics: ['work'], setting: 'work', diff: 3,
    en: '!You’re so lazy!→I did most of | the project | +and I’m tired. | Let’s split | the rest.',
    he: '!את כזאת עצלנית!→{עשיתי|עשיתי} את רוב | הפרויקט | +ואני {עייף|עייפה}. | בואי נחלק | את השאר.',
    ar: '!أنتِ كسولة جدًا!→قمت بمعظم | المشروع | +وأنا متعب. | لنقسم | الباقي.',
  },
  {
    id: 'stranger-moron', with: ['stranger'], face: 'woman', topics: ['road'], setting: 'road', diff: 3,
    en: '!Learn to drive, moron!→That was close. | Please | +be careful | in the parking lot.',
    he: '!תלמדי לנהוג, מטומטמת!→זה היה קרוב. | בבקשה | +תיזהרי | בחניון.',
    ar: '!تعلّمي القيادة يا غبية!→كان ذلك قريبًا. | من فضلك | +انتبهي | في الموقف.',
  },
  {
    id: 'neighbor-crazy', with: ['neighbor'], face: 'grandpa', topics: ['neighbors', 'respect'], setting: 'home', diff: 3,
    en: '!You’re a crazy old man!→I hear you’re bothered | by the music. | Which hours | +are hard for you?',
    he: '!אתה זקן משוגע!→{שומע|שומעת} שהמוזיקה | מפריעה לך. | באילו שעות | +קשה לך?',
    ar: '!أنت عجوز مجنون!→أسمع أن الموسيقى | تزعجك. | في أي ساعات | +يصعب عليك؟',
  },
  {
    id: 'family-dramatic', with: ['family'], face: 'man', topics: ['respect'], setting: 'home', diff: 3,
    en: '!Stop being so dramatic!→I can see it’s big for you. | Let’s talk | +calmly | after dinner.',
    he: '!תפסיק להיות כזה דרמטי!→אני {רואה|רואה} שזה גדול בשבילך. | בוא נדבר | +ברוגע | אחרי הארוחה.',
    ar: '!كفّ عن المبالغة!→أرى أن الأمر كبير بالنسبة لك. | لنتحدث | +بهدوء | بعد العشاء.',
  },
  {
    id: 'boss-thanks-never', with: ['boss'], face: 'man', topics: ['work'], setting: 'work', diff: 4,
    en: '+Thanks for the feedback, | !but you NEVER say anything good→and I’d also love to hear | what worked.',
    he: '+תודה על המשוב, | !אבל אתה אף פעם לא אומר משהו טוב→ו{אשמח|אשמח} לשמוע גם | מה עבד.',
    ar: '+شكرًا على الملاحظات، | !لكنك لا تقول شيئًا جيدًا أبدًا→وأودّ أن أسمع أيضًا | ما الذي نجح.',
  },
  {
    id: 'friend-thanks-always', with: ['friend'], face: 'woman', topics: ['connection'], setting: 'public', diff: 4,
    en: '+I love you, | !but you ALWAYS talk about yourself→and I’d like to share too | about my week.',
    he: '+אני {אוהב|אוהבת} אותך, | !אבל את תמיד מדברת רק על עצמך→והייתי רוצה לשתף גם | על השבוע שלי.',
    ar: '+أحبك، | !لكنك دائمًا تتحدثين عن نفسك→وأودّ أن أشارك أيضًا | عن أسبوعي.',
  },
  {
    id: 'cowork-double', with: ['coworker'], face: 'man', topics: ['work', 'respect'], setting: 'work', diff: 4,
    en: '!You idiot,→Hey, | !you deleted EVERYTHING!→the file got deleted. | Can you | help me restore it?',
    he: '!יא אידיוט,→היי, | !מחקת הכל!→הקובץ נמחק. | תוכל | לעזור לי לשחזר?',
    ar: '!يا غبي،→مرحبًا، | !حذفت كل شيء!→الملف حُذف. | هل يمكنك | مساعدتي في استعادته؟',
  },
  {
    id: 'neighbor-double', with: ['neighbor'], face: 'woman', topics: ['neighbors', 'noise'], setting: 'home', diff: 4,
    en: '!You’re impossible!→I tried to sleep | !and you NEVER stop→and the dog barked | all night. | +I need sleep.',
    he: '!את בלתי אפשרית!→{ניסיתי|ניסיתי} לישון | !ואת אף פעם לא מפסיקה→והכלב נבח | כל הלילה. | +אני {צריך|צריכה} לישון.',
    ar: '!أنتِ مستحيلة!→حاولت أن أنام | !وأنتِ لا تتوقفين أبدًا→والكلب نبح | طوال الليل. | +أحتاج أن أنام.',
  },
  {
    id: 'family-thanks-trap', with: ['family'], face: 'grandma', topics: ['in-laws'], setting: 'home', diff: 4,
    en: '+Thank you for cooking, | !but it’s ALWAYS too much→and next time | let’s cook | +together.',
    he: '+תודה שבישלת, | !אבל זה תמיד יותר מדי→ובפעם הבאה | בואי נבשל | +ביחד.',
    ar: '+شكرًا لأنكِ طبختِ، | !لكنه دائمًا كثير جدًا→وفي المرة القادمة | لنطبخ | +معًا.',
  },
  {
    id: 'friend-neutral-scary', with: ['friend'], face: 'man', topics: ['honesty'], setting: 'online', diff: 4,
    en: 'We need | to talk | about | !what you did, traitor→what happened at the party. | +It matters to me.',
    he: 'אנחנו צריכים | לדבר | על | !מה שעשית, בוגד→מה שקרה במסיבה. | +זה חשוב לי.',
    ar: 'علينا | أن نتحدث | عن | !ما فعلته يا خائن→ما حدث في الحفلة. | +هذا مهم لي.',
  },
  {
    id: 'boss-neutral-scary', with: ['boss'], face: 'woman', topics: ['work'], setting: 'work', diff: 4,
    en: 'About | the deadline: | it won’t happen | !because you’re unrealistic→with the current team. | +Can we talk?',
    he: 'לגבי | הדדליין: | זה לא יקרה | !כי את לא מציאותית→עם הצוות הנוכחי. | +אפשר לדבר?',
    ar: 'بخصوص | الموعد النهائي: | لن يحدث | !لأنكِ غير واقعية→بالفريق الحالي. | +هل نتحدث؟',
  },
  {
    id: 'stranger-double', with: ['stranger'], face: 'man', topics: ['public'], setting: 'online', diff: 4,
    en: '!You people are useless!→I’ve been waiting | !for FORTY minutes, idiots!→for forty minutes. | +I just need | the order fixed.',
    he: '!אתם חסרי תועלת!→אני {מחכה|מחכה} | !ארבעים דקות, אידיוטים!→ארבעים דקות. | +אני רק {צריך|צריכה} | שיתקנו את ההזמנה.',
    ar: '!أنتم عديمو الفائدة!→أنتظر | !منذ أربعين دقيقة يا أغبياء!→منذ أربعين دقيقة. | +أحتاج فقط | تصحيح الطلب.',
  },
  {
    id: 'cowork-thanks-never', with: ['coworker'], face: 'woman', topics: ['work'], setting: 'work', diff: 4,
    en: '+Thanks for covering for me, | !you NEVER do that→it really helped | +— I owe you one.',
    he: '+תודה שהחלפת אותי, | !את אף פעם לא עושה את זה→זה ממש עזר | +— אני {חייב|חייבת} לך.',
    ar: '+شكرًا لأنكِ غطّيتِ مكاني، | !أنتِ لا تفعلين ذلك أبدًا→لقد ساعد كثيرًا | +— أنا مدين لكِ.',
  },
  {
    id: 'family-double', with: ['family'], face: 'man', topics: ['respect'], setting: 'home', diff: 4,
    en: '!You know NOTHING→I see it differently | !about my life, so shut up→and I’d like you to ask | before you judge.',
    he: '!אתה לא יודע כלום→אני {רואה|רואה} את זה אחרת | !על החיים שלי, אז שתוק→ו{אשמח|אשמח} שתשאל | לפני שאתה שופט.',
    ar: '!أنت لا تعرف شيئًا→أرى الأمر بشكل مختلف | !عن حياتي، فاسكت→وأودّ أن تسأل | قبل أن تحكم.',
  },
  {
    id: 'friend-loan-double', with: ['friend'], face: 'man', topics: ['money'], setting: 'online', diff: 4, heavy: true,
    en: '+I care about us, | !but you’re a freeloader→and I need the money back | !— you ALWAYS do this→— by the end of the month.',
    he: '+אכפת לי מאיתנו, | !אבל אתה טפיל→ואני {צריך|צריכה} את הכסף בחזרה | !— אתה תמיד עושה את זה→— עד סוף החודש.',
    ar: '+تهمّني صداقتنا، | !لكنك طفيلي→وأحتاج المال | !— أنت دائمًا تفعل هذا→— حتى نهاية الشهر.',
  },
  {
    id: 'neighbor-thanks', with: ['neighbor'], face: 'grandpa', topics: ['neighbors'], setting: 'home', diff: 4,
    en: '+Thanks for the package, | !but you ALWAYS open my mail→and please | leave it | closed next time.',
    he: '+תודה על החבילה, | !אבל אתה תמיד פותח לי את הדואר→ובבקשה | להשאיר אותה | סגורה בפעם הבאה.',
    ar: '+شكرًا على الطرد، | !لكنك دائمًا تفتح بريدي→ومن فضلك | اتركه | مغلقًا في المرة القادمة.',
  },
  {
    id: 'cowork-feeling-trap', with: ['coworker'], face: 'man', topics: ['work', 'respect'], setting: 'work', diff: 4,
    en: '+I’m frustrated, | +and I respect you, | !but you’re a bully→and I need you to stop | interrupting me.',
    he: '+אני {מתוסכל|מתוסכלת}, | +ואני {מעריך|מעריכה} אותך, | !אבל אתה בריון→ואני {צריך|צריכה} שתפסיק | לקטוע אותי.',
    ar: '+أنا محبط، | +وأحترمك، | !لكنك متنمّر→وأحتاج أن تتوقف | عن مقاطعتي.',
  },
  {
    id: 'friend-neutral-hurt', with: ['friend'], face: 'woman', topics: ['connection'], setting: 'public', diff: 4,
    en: 'You said | you’d come, | !you flaky liar→and you didn’t. | +I waited | +and I was sad.',
    he: 'אמרת | שתבואי, | !שקרנית לא אמינה→ולא באת. | +{חיכיתי|חיכיתי} | +והיה לי עצוב.',
    ar: 'قلتِ | إنكِ ستأتين، | !يا كاذبة متقلّبة→ولم تأتي. | +انتظرت | +وحزنت.',
  },
  {
    id: 'cowork-sting-late', with: ['coworker'], face: 'man', topics: ['work'], setting: 'work', diff: 5,
    en: '~Oh, look who finally decided to show up→The meeting started at nine | — | +I’d like us | to start on time.',
    he: '~אה, תראו מי החליט סוף סוף להופיע→הישיבה התחילה בתשע | — | +{אשמח|אשמח} שנתחיל | בזמן.',
    ar: '~آه، انظروا من قرّر الحضور أخيرًا→بدأ الاجتماع في التاسعة | — | +أودّ أن نبدأ | في الموعد.',
  },
  {
    id: 'boss-sting-great', with: ['boss'], face: 'woman', topics: ['work', 'work-life'], setting: 'work', diff: 5,
    en: '~Great, just what I needed tonight→I can’t finish this tonight. | +I’m worn out. | What can wait | until tomorrow?',
    he: '~מעולה, בדיוק מה שהייתי צריך הלילה→אני לא {יכול|יכולה} לסיים את זה הלילה. | +אני {סחוט|סחוטה}. | מה יכול לחכות | למחר?',
    ar: '~رائع، هذا بالضبط ما كنت أحتاجه الليلة→لا أستطيع إنهاء هذا الليلة. | +أنا منهك. | ما الذي يمكن أن ينتظر | حتى الغد؟',
  },
  {
    id: 'friend-sting-thanks', with: ['friend'], face: 'woman', topics: ['connection'], setting: 'online', diff: 5,
    en: '~Thanks SO much for remembering my birthday→Today is my birthday, | +and I wanted | to hear | from you.',
    he: '~תודה רבה באמת שזכרת את יום ההולדת שלי→היום יום ההולדת שלי, | +ו{רציתי|רציתי} | לשמוע | ממך.',
    ar: '~شكرًا جزيلًا لأنكِ تذكّرتِ عيد ميلادي→اليوم عيد ميلادي، | +وكنت أريد | أن أسمع | منكِ.',
  },
  {
    id: 'family-sting-wonderful', with: ['family'], face: 'grandma', topics: ['in-laws', 'respect'], setting: 'home', diff: 5,
    en: '~Wonderful advice, as always→I hear your advice. | +I’m doing my best | and | !you ALWAYS criticize→I’d love support | +too.',
    he: '~עצה נפלאה, כרגיל→{שמעתי|שמעתי} את העצה. | +אני {עושה|עושה} כמיטב יכולתי | ו | !את תמיד מבקרת→{אשמח|אשמח} לתמיכה | +גם.',
    ar: '~نصيحة رائعة كالعادة→سمعت نصيحتك. | +أبذل قصارى جهدي | و | !أنتِ دائمًا تنتقدين→أودّ الدعم | +أيضًا.',
  },
  {
    id: 'neighbor-sting-party', with: ['neighbor'], face: 'man', topics: ['neighbors', 'noise'], setting: 'home', diff: 5,
    en: '~Lovely party last night, really→The music | was loud | until two. | +I have work at six. | Can we agree | on midnight?',
    he: '~מסיבה מקסימה אתמול, באמת→המוזיקה | הייתה חזקה | עד שתיים. | +אני {עובד|עובדת} בשש. | נסכים | על חצות?',
    ar: '~حفلة جميلة البارحة، حقًّا→الموسيقى | كانت عالية | حتى الثانية. | +عندي عمل في السادسة. | هل نتفق | على منتصف الليل؟',
  },
  {
    id: 'cowork-long', with: ['coworker'], face: 'woman', topics: ['work', 'respect'], setting: 'work', diff: 5,
    en: '!You ALWAYS take the credit!→In the meeting | my part | wasn’t mentioned. | +I feel invisible | !and you don’t care→and I’d like us to present | together | +next time.',
    he: '!את תמיד לוקחת את הקרדיט!→בישיבה | החלק שלי | לא הוזכר. | +אני {מרגיש|מרגישה} {שקוף|שקופה} | !ולא אכפת לך→ו{אשמח|אשמח} שנציג | ביחד | +בפעם הבאה.',
    ar: '!أنتِ دائمًا تأخذين الفضل!→في الاجتماع | لم يُذكر | جزئي. | +أشعر أنني غير مرئي | !ولا يهمّك ذلك→وأودّ أن نعرض | معًا | +في المرة القادمة.',
  },
  {
    id: 'friend-long', with: ['friend'], face: 'man', topics: ['connection', 'honesty'], setting: 'public', diff: 5, heavy: true,
    en: '!You betrayed me!→I told you | something personal | and others | heard it. | +It really hurt. | !You’re a terrible friend→I need to know | +I can trust you.',
    he: '!בגדת בי!→סיפרתי לך | משהו אישי | ואחרים | שמעו את זה. | +זה ממש כאב. | !אתה חבר נוראי→אני {צריך|צריכה} לדעת | +שאפשר לסמוך עליך.',
    ar: '!لقد خنتني!→أخبرتك | بشيء شخصي | والآخرون | سمعوه. | +لقد آلمني كثيرًا. | !أنت صديق سيئ→أحتاج أن أعرف | +أنني أستطيع الوثوق بك.',
  },
  {
    id: 'boss-long', with: ['boss'], face: 'man', topics: ['work', 'respect'], setting: 'work', diff: 5, heavy: true,
    en: '!Don’t you DARE yell at me!→I’d like us to talk | without raising | our voices. | +I felt humiliated | in front of the team. | !You’re a tyrant→Can we talk | +privately?',
    he: '!שלא תעז לצעוק עליי!→{אשמח|אשמח} שנדבר | בלי להרים | את הקול. | +הרגשתי {מושפל|מושפלת} | מול הצוות. | !אתה רודן→אפשר לדבר | +בארבע עיניים?',
    ar: '!إياك أن تصرخ عليّ!→أودّ أن نتحدث | دون أن نرفع | أصواتنا. | +شعرت بالإهانة | أمام الفريق. | !أنت طاغية→هل نتحدث | +على انفراد؟',
  },
  {
    id: 'family-long', with: ['family'], face: 'man', topics: ['in-laws', 'chores'], setting: 'home', diff: 5,
    en: '~Oh sure, I’ll host AGAIN, no problem→I’m happy to host, | +but I’m tired. | !You NEVER help→This time | everyone | brings | one dish.',
    he: '~בטח, אארח שוב, אין בעיה→{שמח|שמחה} לארח, | +אבל אני {עייף|עייפה}. | !אתם אף פעם לא עוזרים→הפעם | כל אחד | מביא | מנה אחת.',
    ar: '~طبعًا، سأستضيف مرة أخرى، لا مشكلة→يسعدني أن أستضيف، | +لكنني متعب. | !أنتم لا تساعدون أبدًا→هذه المرة | كل واحد | يحضر | طبقًا واحدًا.',
  },
  {
    id: 'stranger-sting', with: ['stranger'], face: 'woman', topics: ['public'], setting: 'public', diff: 5,
    en: '~Wow, fantastic service here→This isn’t | what I ordered, | and | +I’m hungry. | How long | for the right dish?',
    he: '~וואו, שירות פנטסטי פה→זה לא | מה {שהזמנתי|שהזמנתי}, | ו | +אני {רעב|רעבה}. | כמה זמן | למנה הנכונה?',
    ar: '~واو، خدمة رائعة هنا→هذا ليس | ما طلبته، | و | +أنا جائع. | كم من الوقت | للطبق الصحيح؟',
  },
  {
    id: 'friend-sting-late', with: ['friend'], face: 'woman', topics: ['respect'], setting: 'public', diff: 5,
    en: '~No worries, I LOVE waiting alone→I waited | half an hour. | +I was glad to see you, | and | next time | +send a message?',
    he: '~אין בעיה, אני מת{|ה} לחכות לבד→{חיכיתי|חיכיתי} | חצי שעה. | +{שמחתי|שמחתי} לראות אותך, | ו | בפעם הבאה | +תשלחי הודעה?',
    ar: '~لا بأس، أحبّ الانتظار وحدي→انتظرت | نصف ساعة. | +سعدت برؤيتك، | و | في المرة القادمة | +أرسلي رسالة؟',
  },
  {
    id: 'boss-sting-weekend', with: ['boss'], face: 'man', topics: ['work', 'work-life'], setting: 'online', diff: 5,
    en: '~Sure, who needs weekends anyway→I’m not available | this weekend. | +Family time matters to me. | !You’re ALWAYS like this→Let’s plan it | for Monday.',
    he: '~בטח, מי צריך סופי שבוע בכלל→אני לא {זמין|זמינה} | בסוף השבוע. | +הזמן הפרטי חשוב לי. | !אתה תמיד ככה→בוא נתכנן את זה | ליום שני.',
    ar: '~طبعًا، من يحتاج عطلات أصلًا→لست متاحًا | في عطلة نهاية الأسبوع. | +وقتي الخاص مهم لي. | !أنت دائمًا هكذا→لنخطط لذلك | يوم الاثنين.',
  },
  {
    id: 'cowork-sting-helpful', with: ['coworker'], face: 'woman', topics: ['work', 'respect'], setting: 'online', diff: 5,
    en: '~Thanks for pointing out my mistake to EVERYONE→Thanks for the fix. | +It embarrassed me | in front of the team. | Next time, | tell me | +first?',
    he: '~תודה שהראית את הטעות שלי לכולם→תודה על התיקון. | +זה {הביך|הביך} אותי | מול הצוות. | בפעם הבאה, | תגידי לי | +קודם?',
    ar: '~شكرًا لأنكِ أظهرتِ خطئي للجميع→شكرًا على التصحيح. | +لقد أحرجني ذلك | أمام الفريق. | في المرة القادمة، | أخبريني | +أولًا؟',
  },
  {
    id: 'family-sting-married', with: ['family'], face: 'woman', topics: ['in-laws', 'respect'], setting: 'home', diff: 5,
    en: '~Great question, Auntie, thanks for asking→When it’s right for me, | I’ll tell you. | !Stop being so nosy→Let’s talk | about | +something else.',
    he: '~שאלה מצוינת, דודה, תודה ששאלת→כשזה יתאים לי, | אספר לך. | !תפסיקי להיות כזאת חטטנית→בואי נדבר | על | +משהו אחר.',
    ar: '~سؤال رائع يا عمّتي، شكرًا على السؤال→حين يناسبني، | سأخبرك. | !كفّي عن الفضول→لنتحدث | عن | +شيء آخر.',
  },
  {
    id: 'neighbor-long', with: ['neighbor'], face: 'woman', topics: ['neighbors', 'road'], setting: 'home', diff: 5,
    en: '!You blocked me AGAIN!→Your car | is behind mine | and | +I’m late for work. | !You’re so inconsiderate→Could you move it now, | and let’s | +find a fix?',
    he: '!חסמת אותי שוב!→הרכב שלך | מאחורי שלי | ו | +אני {מאחר|מאחרת} לעבודה. | !את כל כך לא מתחשבת→תוכלי להזיז עכשיו, | ובואי | +נמצא פתרון?',
    ar: '!سددتِ طريقي مرة أخرى!→سيارتك | خلف سيارتي | و | +أنا متأخر عن العمل. | !أنتِ لا تراعين أحدًا→هل تحرّكينها الآن، | ولنجد | +حلًّا؟',
  },
  {
    id: 'friend-sting-money', with: ['friend'], face: 'man', topics: ['money'], setting: 'online', diff: 5, heavy: true,
    en: '~Nice vacation — paid for with my money?→I saw the photos. | I need | the money back. | +It matters to me. | Can we set | a date?',
    he: '~חופשה יפה, על חשבוני?→{ראיתי|ראיתי} את התמונות. | אני {צריך|צריכה} | את הכסף בחזרה. | +זה חשוב לי. | נקבע | תאריך?',
    ar: '~عطلة جميلة — على حسابي؟→رأيت الصور. | أحتاج | المال. | +هذا مهم لي. | هل نحدد | موعدًا؟',
  },
  {
    id: 'stranger-long', with: ['stranger'], face: 'man', topics: ['road'], setting: 'road', diff: 5,
    en: '!Are you out of your mind?!→You almost hit me | at the crossing. | +I got scared | !you maniac→and | please | +slow down.',
    he: '!יצאת מדעתך?!→כמעט פגעת בי | במעבר החצייה. | +{נבהלתי|נבהלתי} | !משוגע→ו | בבקשה | +תאט.',
    ar: '!هل جننت؟!→كدت تصدمني | عند ممر المشاة. | +خفت | !يا مجنون→و | من فضلك | +خفّف السرعة.',
  },
  {
    id: 'cowork-sting-weekend', with: ['coworker'], face: 'woman', topics: ['work', 'work-life'], setting: 'work', diff: 5,
    en: '~Oh, have a GREAT weekend, while I finish your part→Your part | isn’t done | and | +I’m stressed. | !You ALWAYS leave early→Can we split it | +before you go?',
    he: '~סוף שבוע מעולה לך, בזמן שאני {גומר|גומרת} את החלק שלך→החלק שלך | לא גמור | ו | +אני {לחוץ|לחוצה}. | !את תמיד הולכת מוקדם→נחלק את זה | +לפני שאת הולכת?',
    ar: '~عطلة سعيدة جدًا، بينما أنهي جزءك→جزؤك | لم ينتهِ | و | +أنا متوتر. | !أنتِ دائمًا تغادرين باكرًا→هل نقسّمه | +قبل أن تذهبي؟',
  },
  {
    id: 'neighbor-sting-stairs', with: ['neighbor'], face: 'grandpa', topics: ['neighbors', 'mess'], setting: 'home', diff: 5,
    en: '~Thanks for the lovely smell in the stairwell→Your trash bag | is on the stairs | for days. | +It bothers me. | !You’re disgusting→Could you | take it down | +today?',
    he: '~תודה על הריח הנעים בחדר המדרגות→שקית הזבל שלך | על המדרגות | כבר ימים. | +זה מפריע לי. | !אתה מגעיל→תוכל | להוריד אותה | +היום?',
    ar: '~شكرًا على الرائحة الجميلة على الدرج→كيس قمامتك | على الدرج | منذ أيام. | +هذا يزعجني. | !أنت مقرف→هل يمكنك | إنزاله | +اليوم؟',
  },
  {
    id: 'friend-sting-plans', with: ['friend'], face: 'man', topics: ['connection'], setting: 'online', diff: 5,
    en: '~Sure, let me know if you EVER have time for me→We haven’t met | in two months. | +I miss you | !and you don’t care→Let’s set | a date | +now?',
    he: '~בטח, תגיד לי אם יהיה לך אי פעם זמן בשבילי→לא נפגשנו | חודשיים. | +אני {מתגעגע|מתגעגעת} | !ולא אכפת לך→בוא נקבע | תאריך | +עכשיו?',
    ar: '~طبعًا، أخبرني إن صار عندك وقت لي يومًا→لم نلتقِ | منذ شهرين. | +اشتقت إليك | !ولا يهمّك→هل نحدد | موعدًا | +الآن؟',
  },
];
