import type { Content } from '../content';

export const en: Content = {
  dilemmas: [
    {
      id: 'juice',
      tags: ['parent-young-child', 'parent-school-age', 'mess'],
      situation: 'Grape juice just spilled all over the couch you cleaned this morning.',
      options: [
        { text: 'Oops, it happens. Let’s grab a towel and clean it up together.', v: 'best' },
        { text: 'I need a minute on my own. Then we’ll clean it.', v: 'ok' },
        { text: 'How many times have I said no eating on the couch?!', v: 'bad' },
        { text: 'Great. Just great. Thanks a lot.', v: 'bad' },
      ],
      why: 'Accidents happen. Cleaning up together teaches responsibility — without shame.',
    },
    {
      id: 'remote',
      tags: ['parent-young-child', 'parent-school-age', 'siblings', 'work-life', 'noise'],
      situation: 'The kids have been fighting over the remote for ten minutes, and you’re in the middle of an important call.',
      options: [
        { text: 'Finish the call, then help them agree on turns.', v: 'best' },
        { text: 'Switch off the TV until the call is over.', v: 'ok' },
        { text: 'Yell: “Enough! Nobody’s watching anything!”', v: 'bad' },
        { text: 'Ignore it and turn up the phone.', v: 'bad' },
      ],
      why: 'Close one thing at a time, and offer a fair way forward instead of adding more noise.',
    },
    {
      id: 'milk',
      tags: ['partner', 'household'],
      situation: 'Your partner forgot to buy milk again, and there’s nothing for breakfast tomorrow.',
      options: [
        { text: '“This frustrates me. Let’s find a way so it doesn’t happen again.”', v: 'best' },
        { text: 'Pop out and buy it yourself, without saying a word.', v: 'ok' },
        { text: '“I can’t count on you for anything!”', v: 'bad' },
        { text: 'Slam the fridge and stay silent all evening.', v: 'bad' },
      ],
      why: 'A sentence that starts with “I” says what bothers you without blaming, and opens a shared solution.',
    },
    {
      id: 'dressing',
      tags: ['parent-young-child', 'morning-rush'],
      situation: 'Your little one refuses to get dressed, and you’re already late for daycare.',
      options: [
        { text: '“Do you want the red shirt or the blue one?”', v: 'best' },
        { text: 'Dress him quietly, even while he protests.', v: 'ok' },
        { text: '“If you don’t get dressed now — no tablet for a week!”', v: 'bad' },
        { text: 'Shout “We’re late!” and pull him by the arm.', v: 'bad' },
      ],
      why: 'A small choice gives a child back a sense of control, and the struggle gets shorter.',
    },
    {
      id: 'drum',
      tags: ['parent-young-child', 'siblings', 'noise', 'bedtime'],
      situation: 'The baby just fell asleep, and the big one starts drumming on a pot.',
      options: [
        { text: 'Crouch to his level and whisper: “Let’s drum outside.”', v: 'best' },
        { text: 'Take the pot and hand him something quiet.', v: 'ok' },
        { text: 'Shout “Quiet!” — and the baby wakes up.', v: 'bad' },
        { text: 'Snatch the spoon out of his hand.', v: 'bad' },
      ],
      why: 'Getting down to eye level and offering an alternative stops the noise without waking everyone.',
    },
    {
      id: 'room',
      tags: ['parent-school-age', 'parent-teen', 'chores', 'mess'],
      situation: 'You’ve asked three times for the room to be tidied. Nothing happened.',
      options: [
        { text: '“Let’s tidy together for five minutes. I’m setting a timer.”', v: 'best' },
        { text: '“Once the room is tidy — you can go out and play.”', v: 'ok' },
        { text: '“You never listen to me!”', v: 'bad' },
        { text: 'Stuff everything into a bag and dump it in the storeroom.', v: 'bad' },
      ],
      why: 'Doing it together, with a clear time limit, turns a demand into a task that can actually be done.',
    },
    {
      id: 'dinner',
      tags: ['parent-young-child', 'parent-school-age', 'mealtime'],
      situation: 'You cooked for an hour. The first thing said at the table: “Yuck, I’m not eating that.”',
      options: [
        { text: '“You don’t have to like it. One bite to taste, and there’s bread if you’re hungry.”', v: 'best' },
        { text: '“Next time, help me choose what we cook.”', v: 'ok' },
        { text: '“Eat and be quiet, some kids have no food at all!”', v: 'bad' },
        { text: 'Snatch the plate away with a bang.', v: 'bad' },
      ],
      why: 'Respect his taste and keep the rule — without a power struggle over the plate.',
    },
    {
      id: 'homework',
      tags: ['parent-school-age', 'homework'],
      situation: 'Half an hour on one math sheet, and he “doesn’t get any of it”.',
      options: [
        { text: '“Let’s take a five-minute break and come back to one problem.”', v: 'best' },
        { text: '“We’ll ask the teacher tomorrow. That’s enough for today.”', v: 'ok' },
        { text: '“It’s so simple! What’s so hard?!”', v: 'bad' },
        { text: 'Angrily solve the whole sheet for him yourself.', v: 'bad' },
      ],
      why: 'A frustrated brain doesn’t learn. A short break resets you both.',
    },
    {
      id: 'shoes',
      tags: ['parent-school-age', 'parent-teen', 'partner', 'household', 'mess'],
      situation: 'Someone left shoes in the doorway. You tripped over them. Again.',
      options: [
        { text: '“Ouch. Let’s find the shoes a permanent spot.”', v: 'best' },
        { text: 'Move them aside and talk about it later.', v: 'ok' },
        { text: '“Who’s the slob?! Everyone here, now!”', v: 'bad' },
        { text: 'Kick the shoes to the end of the hallway.', v: 'bad' },
      ],
      why: 'First acknowledge the pain, then fix the problem — a fixed spot saves the next time.',
    },
    {
      id: 'fight',
      tags: ['parent-young-child', 'parent-school-age', 'siblings', 'noise'],
      situation: '“He hit me!” — “She started it!” — both shouting at once.',
      options: [
        { text: '“I hear that you’re both angry. Each of you tells it in turn.”', v: 'best' },
        { text: 'Separate them into different rooms for a few minutes.', v: 'ok' },
        { text: '“You’re both punished! I don’t care who started it!”', v: 'bad' },
        { text: '“Sort it out yourselves” — and walk out slamming the door.', v: 'bad' },
      ],
      why: 'When both sides feel heard, it is much easier for them to calm down.',
    },
    {
      id: 'phone',
      tags: ['parent-young-child', 'parent-school-age', 'parent-teen', 'partner', 'work-life', 'mealtime'],
      situation: 'The phone rings for the fifth time in the middle of dinner. Work, again.',
      options: [
        { text: 'Silence it, say “This is our time now,” and get back to it later.', v: 'best' },
        { text: 'Answer briefly: “I’ll call you back in an hour.”', v: 'ok' },
        { text: 'Answer and argue loudly at the table.', v: 'bad' },
        { text: 'Toss the phone on the couch and grumble all evening.', v: 'bad' },
      ],
      why: 'A clear boundary protects family time — and your patience too.',
    },
    {
      id: 'bedtime',
      tags: ['parent-young-child', 'bedtime'],
      situation: '“I’m thirsty.” “I need to pee.” “One more story!” — the seventh time after lights out.',
      options: [
        { text: '“I love you. Now it’s sleep time. I’ll check on you in five minutes.”', v: 'best' },
        { text: 'Bring water quietly and leave without talking.', v: 'ok' },
        { text: '“If you get up one more time — that’s it!”', v: 'bad' },
        { text: 'Shut the door and ignore the crying.', v: 'bad' },
      ],
      why: 'Warmth and a limit in the same sentence: the child feels safe, and the routine holds.',
    },
    {
      id: 'eyeroll',
      tags: ['parent-teen', 'chores', 'respect'],
      situation: 'You ask for help unloading the dishwasher. An eye roll: “Whatever.”',
      options: [
        { text: '“I saw that. It still needs doing — now or after dinner?”', v: 'best' },
        { text: 'Let it slide and unload it yourself this time.', v: 'ok' },
        { text: '“Don’t you roll your eyes at me! Who do you think you are?”', v: 'bad' },
        { text: '“Sure, I’ll do it. I do everything here anyway.”', v: 'bad' },
      ],
      why: 'Skip the bait, keep the boundary, offer a choice — teens need autonomy, not a power struggle.',
    },
    {
      id: 'curfew',
      tags: ['parent-teen', 'independence'],
      situation: 'Forty minutes past curfew. Your teen isn’t answering. Then the door opens.',
      options: [
        { text: '“I was scared. I’m glad you’re home. We’ll talk tomorrow.”', v: 'best' },
        { text: 'Say nothing tonight and go to bed.', v: 'ok' },
        { text: '“Where were you?! You’re grounded for a month!”', v: 'bad' },
        { text: '“Oh look, someone remembered they live here.”', v: 'bad' },
      ],
      why: 'Relief first, the talk once everyone is calm — a midnight shouting match teaches nothing.',
    },
    {
      id: 'latephone',
      tags: ['parent-teen', 'screens', 'bedtime'],
      situation: '1 a.m., school tomorrow, and the glow of a phone under the blanket.',
      options: [
        { text: '“The phone sleeps in the kitchen tonight. Tomorrow we set a time together.”', v: 'best' },
        { text: 'Take the phone quietly and say you’ll talk tomorrow.', v: 'ok' },
        { text: 'Snatch the phone: “That’s it, you’re never getting it back!”', v: 'bad' },
        { text: '“Fine, be a zombie tomorrow. Not my problem.”', v: 'bad' },
      ],
      why: 'A calm limit now and a rule you make together later beat a midnight confiscation war.',
    },
    {
      id: 'slam',
      tags: ['parent-teen', 'respect', 'connection'],
      situation: '“How was your day?” — “Fine.” The bedroom door slams.',
      options: [
        { text: 'Let it go for now, and knock later with a snack.', v: 'best' },
        { text: 'Text: “Here if you want to talk.”', v: 'ok' },
        { text: 'Open the door: “Don’t you dare slam doors in my house!”', v: 'bad' },
        { text: '“Great talk. Really. Thanks for sharing.”', v: 'bad' },
      ],
      why: 'Not every slammed door needs a response — closeness often comes later, on their timing.',
    },
    {
      id: 'hiddentest',
      tags: ['parent-school-age', 'parent-teen', 'homework', 'honesty'],
      situation: 'You find a failed test crumpled at the bottom of the school bag.',
      options: [
        { text: '“Looks like this one was hard to show me. What happened?”', v: 'best' },
        { text: '“Let’s sit down this weekend and go over it.”', v: 'ok' },
        { text: '“You failed AND you lied to me?!”', v: 'bad' },
        { text: 'Leave it on the table without a word, and wait.', v: 'bad' },
      ],
      why: 'If the truth costs a scene, the next test gets hidden better — curiosity keeps them talking.',
    },
    {
      id: 'ride',
      tags: ['parent-teen', 'independence', 'work-life'],
      situation: 'Ten minutes before an important meeting: “Can you drive me to a friend’s? Like, now?”',
      options: [
        { text: '“Not now. I can at six, or there’s the bus.”', v: 'best' },
        { text: 'Cancel the meeting and drive them.', v: 'ok' },
        { text: '“Do I look like your taxi?!”', v: 'bad' },
        { text: '“Sure. My work doesn’t matter anyway.”', v: 'bad' },
      ],
      why: 'A clear no with options respects both your time and their independence.',
    },
    {
      id: 'tablet',
      tags: ['parent-young-child', 'parent-school-age', 'screens'],
      situation: 'Screen time is over. You take the tablet — and the screaming starts.',
      options: [
        { text: '“You’re mad it’s over. I get it. It’s still over.”', v: 'best' },
        { text: '“Okay, five more minutes, then it’s really done.”', v: 'ok' },
        { text: '“Keep screaming and there’s no tablet all week!”', v: 'bad' },
        { text: '“Wow, what a baby. Very nice.”', v: 'bad' },
      ],
      why: 'Naming the feeling while holding the limit teaches that big feelings are allowed — and limits still stand.',
    },
    {
      id: 'gymclothes',
      tags: ['parent-school-age', 'morning-rush', 'work-life'],
      situation: 'The school calls: gym clothes forgotten. Again. And you’re already at work.',
      options: [
        { text: '“I can’t come. Tonight we’ll make a checklist for the bag together.”', v: 'best' },
        { text: 'Drive over, drop them off, say nothing.', v: 'ok' },
        { text: '“You’d forget your head if it wasn’t attached!”', v: 'bad' },
        { text: 'Bring them, with a sigh the whole office can hear.', v: 'bad' },
      ],
      why: 'A small natural consequence plus a tool for next time beats rescuing and resenting.',
    },
    {
      id: 'toothbrush',
      tags: ['parent-young-child', 'parent-school-age', 'honesty', 'bedtime'],
      situation: '“I brushed my teeth!” The toothbrush is bone dry.',
      options: [
        { text: '“Hmm, this brush is dry. Let’s go do it — I’ll time you.”', v: 'best' },
        { text: '“Go brush them, please.”', v: 'ok' },
        { text: '“Liar! I can’t believe a word you say!”', v: 'bad' },
        { text: '“Sure you did. And I’m the Queen of England.”', v: 'bad' },
      ],
      why: 'Point to the fact without a label — kids who get called liars learn to lie better.',
    },
    {
      id: 'checkout',
      tags: ['parent-young-child', 'public'],
      situation: 'Checkout line, candy at eye level. Your child throws themselves on the floor, screaming.',
      options: [
        { text: 'Kneel, stay close and wait: “You really wanted it.”', v: 'best' },
        { text: 'Leave the cart and carry them outside to calm down.', v: 'ok' },
        { text: '“Get up right now or we’re never coming here again!”', v: 'bad' },
        { text: 'Loudly, to the line: “Kids, huh? Anyone want one?”', v: 'bad' },
      ],
      why: 'Your calm is the anchor — the tantrum passes faster when you don’t join it.',
    },
    {
      id: 'playground',
      tags: ['parent-young-child', 'public'],
      situation: 'At the playground your kid pushes another child. The other parent glares at you.',
      options: [
        { text: 'Check on the other child, then to yours: “Pushing hurts. Let’s take a break.”', v: 'best' },
        { text: 'Apologize to the parent and leave the playground.', v: 'ok' },
        { text: 'Yank their arm: “What is WRONG with you?!”', v: 'bad' },
        { text: '“Kids push. Maybe yours needs to toughen up.”', v: 'bad' },
      ],
      why: 'Care for the hurt child, a calm limit for yours — shaming in public only adds fuel.',
    },
    {
      id: 'nightwake',
      tags: ['parent-young-child', 'bedtime'],
      situation: '3 a.m. The third time tonight: “I can’t sleep…”',
      options: [
        { text: 'Walk them back, a short hug: “Night is for sleeping. I’m right next door.”', v: 'best' },
        { text: 'Let them into your bed, just to get some sleep.', v: 'ok' },
        { text: '“Enough! Back to your room, NOW!”', v: 'bad' },
        { text: 'Pretend to be asleep and hope they give up.', v: 'bad' },
      ],
      why: 'Boring, warm and consistent at night — the less drama, the faster sleep comes back.',
    },
    {
      id: 'dishes',
      tags: ['partner', 'chores'],
      situation: 'You asked this morning. The sink is still full, and your partner’s on the couch.',
      options: [
        { text: '“I’m wiped out. Can you do the dishes before the show?”', v: 'best' },
        { text: 'Do them yourself, and bring it up tomorrow.', v: 'ok' },
        { text: '“You never do anything around here!”', v: 'bad' },
        { text: 'Clatter every plate so it’s clear who’s doing them.', v: 'bad' },
      ],
      why: 'A soft start with a clear request beats criticism — the first minutes set the tone for the whole talk.',
    },
    {
      id: 'scrolling',
      tags: ['partner', 'connection', 'screens'],
      situation: 'You’re telling your partner about a hard day. They’re scrolling their phone.',
      options: [
        { text: '“Five minutes, just me? Can the phone wait?”', v: 'best' },
        { text: 'Stop mid-sentence and wait until they look up.', v: 'ok' },
        { text: '“Talking to you is like talking to a wall!”', v: 'bad' },
        { text: '“Never mind. It’s not important. Nothing I say is.”', v: 'bad' },
      ],
      why: 'Asking for what you need is a bid for connection — criticism only pushes it away.',
    },
    {
      id: 'latehome',
      tags: ['partner', 'mealtime', 'work-life'],
      situation: 'Dinner’s been on the table for an hour. Your partner walks in — no call, no text.',
      options: [
        { text: '“I was worried, and the food went cold. Next time, just text?”', v: 'best' },
        { text: 'Heat up a plate and save the talk for later.', v: 'ok' },
        { text: '“Where were you?! You don’t care about this family at all!”', v: 'bad' },
        { text: '“Dinner? Oh, we ate. Hours ago.”', v: 'bad' },
      ],
      why: 'Saying what you felt and asking for one concrete thing gets further than a trial.',
    },
    {
      id: 'purchase',
      tags: ['partner', 'money'],
      situation: 'A big new charge on the card. Your partner didn’t mention it.',
      options: [
        { text: '“That gave me a shock. Can we agree on an amount we check first?”', v: 'best' },
        { text: '“Let’s go over the budget together this weekend.”', v: 'ok' },
        { text: '“Are you out of your mind? We can’t afford this!”', v: 'bad' },
        { text: 'Buy something just as pricey — see how they like it.', v: 'bad' },
      ],
      why: 'Money fights are about security; naming the worry and agreeing a rule beats tit-for-tat.',
    },
    {
      id: 'overrule',
      tags: ['partner', 'parent-young-child', 'parent-school-age', 'respect'],
      situation: 'You said no dessert. Your partner, in front of the kids: “Oh, let them have some.”',
      options: [
        { text: 'Later, privately: “In front of the kids, we’re a team. Okay?”', v: 'best' },
        { text: 'Say nothing and let it go this time.', v: 'ok' },
        { text: '“Great, now I’m the bad guy! Thanks a lot!”', v: 'bad' },
        { text: 'Next time, overrule them in front of the kids too.', v: 'bad' },
      ],
      why: 'Disagree in private, stand together in public — kids feel safer when parents are a team.',
    },
    {
      id: 'mentalload',
      tags: ['women', 'partner', 'mental-load'],
      situation: '“Just tell me what needs doing and I’ll help!” — while you’re tracking everything in your head.',
      options: [
        { text: '“I don’t need a helper. Take the whole school thing — start to finish.”', v: 'best' },
        { text: 'Write the list for them this time.', v: 'ok' },
        { text: '“Why do I have to think of EVERYTHING in this house?!”', v: 'bad' },
        { text: '“Never mind, it’s faster if I just do it myself.”', v: 'bad' },
      ],
      why: 'The planning load falls mostly on women — hand over a whole task, noticing included, not a to-do item.',
    },
    {
      id: 'formdeadline',
      tags: ['women', 'partner', 'mental-load', 'parent-school-age'],
      situation: 'The school form deadline has passed. Your partner: “Why didn’t you remind me?”',
      options: [
        { text: '“I’m not the reminder. Let’s really split who owns what.”', v: 'best' },
        { text: 'Sign it yourself tomorrow and move on.', v: 'ok' },
        { text: '“Because I’m not your MOTHER!”', v: 'bad' },
        { text: '“Sure, I’ll add ‘remind you’ to my list of everything.”', v: 'bad' },
      ],
      why: 'The anger is about who’s expected to remember — splitting ownership, not just tasks, eases it.',
    },
    {
      id: 'babysitting',
      tags: ['men', 'parent-young-child', 'respect'],
      situation: 'Out alone with the kids, a neighbor grins: “Babysitting today? Where’s Mom?”',
      options: [
        { text: 'Smile: “Nope, just parenting. We’re off to the park.”', v: 'best' },
        { text: 'Shrug it off and keep walking.', v: 'ok' },
        { text: '“Babysitting?! They’re MY kids!”', v: 'bad' },
        { text: '“Yeah, she finally trusted me with them for an hour.”', v: 'bad' },
      ],
      why: 'A light, confident reply sets the record straight without letting a stereotype ruin your day.',
    },
    {
      id: 'badday',
      tags: ['men', 'work-life', 'mess'],
      situation: 'Your boss humiliated you today. At home, one toy on the floor — and you’re about to blow.',
      options: [
        { text: 'Stop at the door: “Rough day. Give me ten minutes, then I’m all yours.”', v: 'best' },
        { text: 'Go straight to the shower without a word.', v: 'ok' },
        { text: '“Who left this here?! Does anyone ever clean up?!”', v: 'bad' },
        { text: 'Kick the toy aside and go silent all evening.', v: 'bad' },
      ],
      why: 'Men often show hurt as anger — naming the real source keeps it from landing on the people at home.',
    },
    {
      id: 'samequestion',
      tags: ['adult-child', 'caregiving', 'health'],
      situation: 'Your mother asks what day it is — for the fourth time this hour.',
      options: [
        { text: 'Answer gently, and write it big on a board on the fridge.', v: 'best' },
        { text: 'Answer again, through clenched teeth.', v: 'ok' },
        { text: '“I JUST told you! Are you even listening?!”', v: 'bad' },
        { text: '“Same day as five minutes ago, Mom.”', v: 'bad' },
      ],
      why: 'The repeating isn’t on purpose — a patient answer plus a written cue helps you both.',
    },
    {
      id: 'carkeys',
      tags: ['adult-child', 'caregiving', 'health', 'independence'],
      situation: 'Your father scraped the car again, and still insists he’s “driving just fine”.',
      options: [
        { text: '“Dad, this scares me. Let’s go for a driving check together.”', v: 'best' },
        { text: 'Quietly take over the errands that need the car.', v: 'ok' },
        { text: '“You’re going to kill someone! Give me the keys, NOW!”', v: 'bad' },
        { text: 'Hide the keys and play dumb when he looks for them.', v: 'bad' },
      ],
      why: 'Giving up the keys means giving up independence — leading with worry and a neutral check keeps his dignity.',
    },
    {
      id: 'homeaide',
      tags: ['adult-child', 'caregiving'],
      situation: 'You finally found a home aide. Your mother sends her away on day one.',
      options: [
        { text: '“You want to manage on your own. What would make her help feel okay?”', v: 'best' },
        { text: 'Cancel the aide and come over more often yourself.', v: 'ok' },
        { text: '“Do you know what I went through to find her?!”', v: 'bad' },
        { text: '“Fine. Just don’t call me when you fall.”', v: 'bad' },
      ],
      why: 'Resistance is often about losing control — asking what would feel okay lets her keep some.',
    },
    {
      id: 'brotherturn',
      tags: ['adult-child', 'siblings', 'caregiving'],
      situation: 'Your brother cancels his turn with Dad again: “Work is crazy.” It’s all on you. Again.',
      options: [
        { text: '“I’m running on empty. Can you take Sundays, or chip in for help?”', v: 'best' },
        { text: 'Cover his turn and vent to a friend later.', v: 'ok' },
        { text: '“You’ve NEVER done anything for this family!”', v: 'bad' },
        { text: '“Sure. I don’t have a job or a life anyway.”', v: 'bad' },
      ],
      why: 'A concrete request with options turns resentment into a fairer split.',
    },
    {
      id: 'momcomment',
      tags: ['adult-child', 'respect', 'mess'],
      situation: 'Your mother, in front of the kids: “How can you live in such a mess?”',
      options: [
        { text: '“Mom, that stings in front of them. Let’s talk later.”', v: 'best' },
        { text: 'Change the subject and put the kettle on.', v: 'ok' },
        { text: '“Nothing I did was EVER good enough for you!”', v: 'bad' },
        { text: '“Thanks, Mom. Always lovely to see you.”', v: 'bad' },
      ],
      why: 'A short, calm boundary protects you — without reopening a decades-old fight in front of the kids.',
    },
    {
      id: 'techcall',
      tags: ['adult-child', 'caregiving', 'work-life'],
      situation: 'Mid-deadline, Dad calls for the fifth time: “The phone’s broken again.”',
      options: [
        { text: '“Not now. Seven o’clock, video call, we’ll fix it together.”', v: 'best' },
        { text: 'Drop everything and walk him through it.', v: 'ok' },
        { text: '“Dad! I’m WORKING! Stop calling me!”', v: 'bad' },
        { text: 'Silence it and let it ring. Five times.', v: 'bad' },
      ],
      why: 'A set time respects his need and your work — without shutting him out.',
    },
    {
      id: 'grandmasweets',
      tags: ['parent-young-child', 'in-laws', 'mealtime'],
      situation: 'You said no sweets before dinner. Grandma, with a wink: “Our little secret.”',
      options: [
        { text: 'Later, quietly: “I know you love spoiling them. Sweets after dinner, okay?”', v: 'best' },
        { text: 'Let it go — it’s grandma’s house.', v: 'ok' },
        { text: '“Why do you ALWAYS undermine me?!”', v: 'bad' },
        { text: '“Sure. And you can come put them to bed on a sugar high.”', v: 'bad' },
      ],
      why: 'Assume good intent and name the rule in private — you keep the boundary and the relationship.',
    },
    {
      id: 'inmyday',
      tags: ['parent-young-child', 'in-laws', 'respect'],
      situation: 'Your mother-in-law, watching you soothe the baby: “In my day, we let them cry.”',
      options: [
        { text: '“A lot has changed. This is what works for us.”', v: 'best' },
        { text: 'Nod and keep doing what you’re doing.', v: 'ok' },
        { text: '“And look how THAT turned out!”', v: 'bad' },
        { text: 'Hand her the baby: “Go ahead then, you do it.”', v: 'bad' },
      ],
      why: 'A short, friendly “this works for us” sets the boundary without turning advice into a battle.',
    },
    {
      id: 'grandadvice',
      tags: ['grandparent', 'respect', 'in-laws'],
      situation: 'You gently suggest a jacket for your grandchild. Your son snaps: “I know what I’m doing!”',
      options: [
        { text: '“You’re right, they’re your kids. Done.”', v: 'best' },
        { text: 'Say nothing, and bring the jacket along anyway.', v: 'ok' },
        { text: '“Excuse me for caring about my own grandchild!”', v: 'bad' },
        { text: '“Fine. Next time find someone else to babysit.”', v: 'bad' },
      ],
      why: 'Grandparents earn closeness by following the parents’ lead — backing off now keeps the door open.',
    },
    {
      id: 'grandbedtime',
      tags: ['grandparent', 'bedtime'],
      situation: 'Babysitting the grandkids. Bedtime. “Mom lets us stay up till ten!”',
      options: [
        { text: '“Nice try. At Grandma and Grandpa’s, it’s bed at eight — with a story.”', v: 'best' },
        { text: 'Call their parents to check the rule.', v: 'ok' },
        { text: '“I don’t care what your mother lets you do!”', v: 'bad' },
        { text: '“Fine, stay up. Tomorrow you’re your parents’ problem.”', v: 'bad' },
      ],
      why: 'Warm and firm, with a bit of humor — kids are testing limits, not your love.',
    },
  ],
  shouts: [
    'Daaaad!',
    'Muuuum!',
    'I’m bored!',
    'He touched me!',
    'Where are my socks?',
    'I’m hungry!!',
    'Look! Look! Look!',
    'Why? Why? Why?',
    'She took mine!',
    'Five more minutes!',
  ],
  notifs: [
    { app: 'P', color: '#25d366', title: 'Class parents', body: '47 new messages' },
    { app: 'W', color: '#4d96ff', title: 'The boss', body: 'Got a minute? It’s urgent' },
    { app: '$', color: '#ff9f1c', title: 'Electric bill', body: 'Payment failed' },
    { app: '!', color: '#e5383b', title: 'System update', body: 'Restart required now' },
    { app: 'G', color: '#b983ff', title: 'Grandma', body: 'Why didn’t you call?' },
    { app: '📦', color: '#8d6e63', title: 'Deliveries', body: 'The courier couldn’t find your address' },
  ],
  lures: ['Tap me!', 'Hurry!!', 'Just one tap', 'Don’t miss out!'],
};
