import type { Meta, Other } from '../../shared/library';
import type { HouseholdTag } from '../../shared/tags';

/**
 * Who each dilemma happens with, and what it's about — the same in every
 * language, so it lives here once. The language files hold only the words.
 */

const KIDS: HouseholdTag[] = ['parent-young-child', 'parent-school-age', 'parent-teen', 'single-parent'];

export const DILEMMA_META: Meta[] = [
  { id: 'juice', with: ['young-child', 'child'], topics: ['mess'], setting: 'home', diff: 1 },
  { id: 'remote', with: ['kids'], topics: ['siblings', 'work-life', 'noise'], setting: 'home', diff: 2 },
  { id: 'milk', with: ['partner'], topics: ['household'], setting: 'home', diff: 1 },
  { id: 'dressing', with: ['young-child'], topics: ['morning-rush'], setting: 'home', diff: 1 },
  { id: 'drum', with: ['young-child'], topics: ['siblings', 'noise', 'bedtime'], setting: 'home', diff: 2 },
  { id: 'room', with: ['child', 'teen'], topics: ['chores', 'mess'], setting: 'home', diff: 1 },
  { id: 'dinner', with: ['young-child', 'child'], topics: ['mealtime'], setting: 'home', diff: 1 },
  { id: 'homework', with: ['child'], topics: ['homework'], setting: 'home', diff: 2 },
  { id: 'shoes', with: ['child', 'teen', 'partner'], topics: ['household', 'mess'], setting: 'home', diff: 1 },
  { id: 'fight', with: ['young-child', 'child'], topics: ['siblings', 'noise'], setting: 'home', diff: 2 },
  { id: 'phone', with: ['kids', 'partner'], topics: ['work-life', 'mealtime'], setting: 'home', diff: 2 },
  { id: 'bedtime', with: ['young-child'], topics: ['bedtime'], setting: 'home', diff: 2 },
  { id: 'eyeroll', with: ['teen'], topics: ['chores', 'respect'], setting: 'home', diff: 2 },
  { id: 'curfew', with: ['teen'], topics: ['independence'], setting: 'home', diff: 3 },
  { id: 'latephone', with: ['teen'], topics: ['screens', 'bedtime'], setting: 'home', diff: 2 },
  { id: 'slam', with: ['teen'], topics: ['respect', 'connection'], setting: 'home', diff: 3 },
  { id: 'hiddentest', with: ['child', 'teen'], topics: ['homework', 'honesty'], setting: 'home', diff: 3 },
  { id: 'ride', with: ['teen'], topics: ['independence', 'work-life'], setting: 'home', diff: 2 },
  { id: 'tablet', with: ['young-child', 'child'], topics: ['screens'], setting: 'home', diff: 2 },
  { id: 'gymclothes', with: ['child'], topics: ['morning-rush', 'work-life'], setting: 'work', diff: 2 },
  { id: 'toothbrush', with: ['young-child', 'child'], topics: ['honesty', 'bedtime'], setting: 'home', diff: 1 },
  { id: 'checkout', with: ['young-child'], topics: ['public'], setting: 'public', diff: 3 },
  { id: 'playground', with: ['young-child'], topics: ['public'], setting: 'public', diff: 3 },
  { id: 'nightwake', with: ['young-child'], topics: ['bedtime'], setting: 'home', diff: 3 },
  { id: 'dishes', with: ['partner'], topics: ['chores'], setting: 'home', diff: 1 },
  { id: 'scrolling', with: ['partner'], topics: ['connection', 'screens'], setting: 'home', diff: 2 },
  { id: 'latehome', with: ['partner'], topics: ['mealtime', 'work-life'], setting: 'home', diff: 2 },
  { id: 'purchase', with: ['partner'], topics: ['money'], setting: 'home', diff: 3, heavy: true },
  { id: 'overrule', with: ['partner'], requires: KIDS, topics: ['respect'], setting: 'home', diff: 3 },
  { id: 'mentalload', with: ['partner'], gender: 'women', topics: ['mental-load'], setting: 'home', diff: 3 },
  { id: 'formdeadline', with: ['partner'], requires: ['parent-school-age', 'parent-teen'], gender: 'women', topics: ['mental-load'], setting: 'home', diff: 3 },
  { id: 'babysitting', with: ['neighbor'], requires: ['parent-young-child', 'parent-school-age'], gender: 'men', topics: ['respect'], setting: 'public', diff: 3 },
  { id: 'badday', with: ['boss'], requires: KIDS, gender: 'men', topics: ['work-life', 'mess'], setting: 'home', diff: 4, heavy: true },
  { id: 'samequestion', with: ['ageing-parent'], topics: ['caregiving', 'health'], setting: 'home', diff: 3, heavy: true },
  { id: 'carkeys', with: ['ageing-parent'], topics: ['caregiving', 'health', 'independence'], setting: 'home', diff: 4, heavy: true },
  { id: 'homeaide', with: ['ageing-parent'], topics: ['caregiving'], setting: 'home', diff: 3, heavy: true },
  { id: 'brotherturn', with: ['family'], requires: ['adult-child'], topics: ['caregiving'], setting: 'home', diff: 3 },
  { id: 'momcomment', with: ['family'], requires: KIDS, topics: ['respect', 'mess', 'in-laws'], setting: 'home', diff: 3 },
  { id: 'techcall', with: ['ageing-parent'], topics: ['caregiving', 'work-life'], setting: 'work', diff: 2 },
  { id: 'grandmasweets', with: ['family'], requires: ['parent-young-child', 'parent-school-age'], topics: ['in-laws', 'mealtime'], setting: 'home', diff: 2 },
  { id: 'inmyday', with: ['family'], requires: ['parent-young-child'], topics: ['in-laws', 'respect'], setting: 'home', diff: 3 },
  { id: 'grandadvice', with: ['family'], requires: ['grandparent'], topics: ['in-laws', 'respect'], setting: 'home', diff: 3 },
  { id: 'grandbedtime', with: ['grandchild'], topics: ['bedtime'], setting: 'home', diff: 2 },
  { id: 'handoff', with: ['kids'], requires: ['single-parent'], topics: ['bedtime'], setting: 'home', diff: 3 },
  { id: 'nobackup', with: ['young-child', 'child'], requires: ['single-parent'], topics: ['health', 'work-life'], setting: 'home', diff: 4, heavy: true },
  { id: 'credit', with: ['coworker'], topics: ['work', 'respect'], setting: 'work', diff: 3 },
  { id: 'lastminute', with: ['boss'], topics: ['work', 'work-life'], setting: 'work', diff: 2 },
  { id: 'replyall', with: ['coworker'], topics: ['work', 'respect'], setting: 'online', diff: 2 },
  { id: 'meetinglate', with: ['coworker'], topics: ['work'], setting: 'work', diff: 1 },
  { id: 'interrupt', with: ['coworker'], topics: ['work', 'respect'], setting: 'work', diff: 2 },
  { id: 'bossyell', with: ['boss'], topics: ['work', 'respect'], setting: 'work', diff: 4, heavy: true },
  { id: 'printer', with: ['none'], topics: ['work'], setting: 'work', diff: 1 },
  { id: 'lunchfridge', with: ['coworker'], topics: ['work'], setting: 'work', diff: 1 },
  { id: 'client', with: ['stranger'], topics: ['work', 'respect'], setting: 'work', diff: 3 },
  { id: 'cutoff', with: ['stranger'], topics: ['road'], setting: 'road', diff: 2 },
  { id: 'parking', with: ['stranger'], topics: ['road'], setting: 'road', diff: 2 },
  { id: 'queue', with: ['stranger'], topics: ['public'], setting: 'public', diff: 1 },
  { id: 'hold', with: ['stranger'], topics: ['public'], setting: 'online', diff: 2 },
  { id: 'package', with: ['stranger'], topics: ['public', 'money'], setting: 'online', diff: 1 },
  { id: 'traffic', with: ['none'], topics: ['road'], setting: 'road', diff: 1 },
  { id: 'laptopcrash', with: ['none'], topics: ['work'], setting: 'work', diff: 2 },
  { id: 'cinema', with: ['stranger'], topics: ['public', 'noise'], setting: 'public', diff: 1 },
  { id: 'waiter', with: ['stranger'], topics: ['public'], setting: 'public', diff: 1 },
  { id: 'drill', with: ['neighbor'], topics: ['neighbors', 'noise'], setting: 'home', diff: 1 },
  { id: 'party', with: ['neighbor'], topics: ['neighbors', 'noise'], setting: 'home', diff: 2 },
  { id: 'blocked', with: ['neighbor'], topics: ['neighbors', 'road'], setting: 'home', diff: 2 },
  { id: 'stairtrash', with: ['neighbor'], topics: ['neighbors', 'mess'], setting: 'home', diff: 1 },
  { id: 'rudeneighbor', with: ['neighbor'], topics: ['neighbors', 'respect'], setting: 'home', diff: 2 },
  { id: 'cancel', with: ['friend'], topics: ['connection'], setting: 'public', diff: 2 },
  { id: 'latefriend', with: ['friend'], topics: ['respect'], setting: 'public', diff: 1 },
  { id: 'friendloan', with: ['friend'], topics: ['money'], setting: 'online', diff: 3, heavy: true },
  { id: 'secret', with: ['friend'], topics: ['honesty', 'connection'], setting: 'public', diff: 4, heavy: true },
  { id: 'groupchat', with: ['friend'], topics: ['respect'], setting: 'online', diff: 3 },
  { id: 'birthday', with: ['friend'], topics: ['connection'], setting: 'online', diff: 2 },
  { id: 'whenmarried', with: ['family'], topics: ['in-laws', 'respect'], setting: 'home', diff: 2 },
  { id: 'compare', with: ['family'], topics: ['respect'], setting: 'home', diff: 3 },
  { id: 'hosting', with: ['family'], topics: ['chores', 'in-laws'], setting: 'home', diff: 2 },
  { id: 'politics', with: ['family'], topics: ['respect'], setting: 'home', diff: 2 },
  { id: 'rmdishes', with: ['roommate'], topics: ['chores', 'mess'], setting: 'home', diff: 1 },
  { id: 'rmguest', with: ['roommate'], topics: ['household'], setting: 'home', diff: 2 },
  { id: 'rmrent', with: ['roommate'], topics: ['money'], setting: 'home', diff: 3, heavy: true },
  { id: 'rmfood', with: ['roommate'], topics: ['household'], setting: 'home', diff: 1 },
  { id: 'rmexam', with: ['roommate'], topics: ['noise'], setting: 'home', diff: 2 },
  { id: 'weekendplans', with: ['partner'], topics: ['connection'], setting: 'home', diff: 2 },
  { id: 'inlawsvisit', with: ['partner'], topics: ['in-laws'], setting: 'home', diff: 2 },
  { id: 'towel', with: ['partner'], topics: ['mess', 'household'], setting: 'home', diff: 1 },
  { id: 'reservation', with: ['partner'], topics: ['connection'], setting: 'public', diff: 2 },
  { id: 'doctor', with: ['ageing-parent'], topics: ['caregiving', 'health'], setting: 'home', diff: 3, heavy: true },
  { id: 'nevervisit', with: ['ageing-parent'], topics: ['caregiving', 'respect'], setting: 'public', diff: 3, heavy: true },
  { id: 'grandscreens', with: ['grandchild'], topics: ['screens', 'connection'], setting: 'home', diff: 2 },
  { id: 'grandcancel', with: ['family'], requires: ['grandparent'], topics: ['connection'], setting: 'home', diff: 2 },
  { id: 'burnt', with: ['none'], topics: ['household'], setting: 'home', diff: 1 },
  { id: 'keys', with: ['none'], topics: ['household'], setting: 'home', diff: 1 },
];

/** Who's shouting, in the order of the language files' shouts (kids first, then the rest of life). */
export const SHOUT_WITH: Other[][] = [
  ...Array.from({ length: 10 }, (): Other[] => ['kids']),
  ['coworker'],
  ['neighbor'],
  ['none'],
  ['roommate'],
  ['partner'],
  ['ageing-parent'],
  ['stranger'],
  ['boss'],
  ['grandchild'],
  ['family'],
];

/** Who each notification is from, in the order of the language files' notifs. */
export const NOTIF_WITH: Other[][] = [
  ['child', 'teen'],
  ['boss'],
  ['none'],
  ['none'],
  ['kids'],
  ['stranger'],
  ['family'],
  ['neighbor'],
  ['coworker'],
  ['partner'],
  ['roommate'],
  ['friend'],
  ['none'],
];
